# Currency Rates

Notebook used to update the latest currency rates from Yahoo Finance. Used before it was automated using Lambda function.

In [1]:
import yfinance as yf
import pandas as pd
from datetime import date

In [2]:
currency_codes = {
    'United States': 'USD',  # US Dollar
    'Japan': 'JPY',  # Japanese Yuan
    'United Kingdom': 'GBP',  # Great British Pound
    'Canada': 'CAD',  # Canadian Dollar
    'France': '',
    'Switzerland': 'CHF',  # Swiss Frank
    'Germany': '',
    'Australia': 'AUD',  # Australian Dollar
    'Netherlands': '',
    'Denmark': 'DKK',  # Danish Krone
    'Sweden': 'SEK',  # Swedish Krona
    'Spain': '',
    'Hong Kong': 'HKD',  # Hong Kong Dollar
    'Italy': '',
    'Singapore': 'SGD',  # Singapore Dollar
    'Finland': '',
    'Belgium': '',
    'Norway': 'NOK',  # Norwegian Krone
    'Israel': 'ILS',  # Israeli Shekel
    'Ireland': '',
    'New Zealand': 'NZD',  # New Zealand Dollar
    'Austria': '',
    'Portugal': '',
    'Eurozona': '',

    'China': 'CNY',  # Chinese Yuan
    'Taiwan': 'TWD',  # New Taiwan Dollar
    'India': 'INR',  # Indian Rupee
    'Korea': 'KRW',  # South Korean Won
    'Brazil': 'BRL',  # Brazilian Real
    'Saudi Arabia': 'SAR',  # Saudi Riyal
    'South Africa': 'ZAR',  # South African Rand
    'Mexico': 'MXN',  # Mexican Peso
    'Thailand': 'THB',  # Thai Baht
    'Indonesia': 'IDR',  # Indonesian Rupiah
    'Malaysia': 'MYR',  # Malaysian Ringgit
    'United Arab Emirates': 'AED',  # UEA Dirham
    'Qatar': 'QAR',  # Qatari Riyal
    'Kuwait': 'KWD',  # Kuwaiti Dinar
    'Turkiye': 'TRY',  # Turkish Lira
    'Philippines': 'PHP',  # Philippine Peso
    'Poland': 'PLN',  # Polish Zloty
    'Chile': 'CLP',  # Chilean Peso
    'Greece': '',
    'Peru': 'PEN',  # Peru Sol
    'Hungary': 'HUF',  # Hungarian Forint
    'Czechia': 'CZK',  # Czech Korona
    'Egypt': 'EGP',  # Egyptian Pound
    'Colombia': 'COP',  # Colombian Peso
    'Argentina': 'ARS',  # Argentinian Peso
    'Russia': 'RUB'  # Russian Ruble
}

In [3]:
historic_data = pd.read_csv('market_data/currency_rates.csv', parse_dates=True,
                            index_col=0)
historic_data.tail()

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Denmark,...,Poland,Chile,Greece,Peru,Hungary,Czechia,Egypt,Colombia,Argentina,Russia
2023-10-02,1.0565,157.962,0.8663,1.4339,1,0.9671,1,1.6410,1,7.4560,...,4.6200,940.36,1.0,3.9407,389.518,24.3552,32.6326,4259.5000,371.2703,102.2500
2023-10-03,1.0481,157.042,0.8667,1.4333,1,0.9620,1,1.6472,1,7.4565,...,4.6165,925.23,1.0,3.9142,388.620,24.4182,32.3920,4247.7002,366.8130,104.1400
2023-10-04,1.0472,156.160,0.8667,1.4347,1,0.9642,1,1.6594,1,7.4573,...,4.6286,938.01,1.0,3.8993,389.489,24.5028,32.3490,4310.1001,366.4262,104.7519
2023-10-05,1.0507,156.507,0.8656,1.4440,1,0.9632,1,1.6597,1,7.4564,...,4.6044,950.48,1.0,3.9070,387.078,24.3809,32.3370,4379.8999,367.7633,105.4043
2023-10-06,1.0550,157.046,0.8645,1.4453,1,0.9625,1,1.6565,1,7.4573,...,4.5925,963.94,1.0,4.0138,386.996,24.4475,32.4695,4583.1602,369.0354,106.6120

In [4]:
start_date = historic_data.last_valid_index()

In [5]:
end_date = date.today()
end_date = str(end_date)
end_date

'2023-12-17'

In [6]:
df = pd.DataFrame(index=pd.date_range(start_date, end_date, freq='B'),
                  columns=currency_codes)


for country in currency_codes:
    currency_code = currency_codes[country]
    if currency_code != '':
        currency_rates = yf.download(f'{currency_code}=X', start_date)
        print(country, currency_rates.shape)
        df[country] = currency_rates['Adj Close']

[*********************100%%**********************]  1 of 1 completed
United States (52, 6)
[*********************100%%**********************]  1 of 1 completed
Japan (52, 6)
[*********************100%%**********************]  1 of 1 completed
United Kingdom (52, 6)
[*********************100%%**********************]  1 of 1 completed
Canada (52, 6)
[*********************100%%**********************]  1 of 1 completed
Switzerland (52, 6)
[*********************100%%**********************]  1 of 1 completed
Australia (52, 6)
[*********************100%%**********************]  1 of 1 completed
Denmark (52, 6)
[*********************100%%**********************]  1 of 1 completed
Sweden (52, 6)
[*********************100%%**********************]  1 of 1 completed
Hong Kong (52, 6)
[*********************100%%**********************]  1 of 1 completed
Singapore (52, 6)
[*********************100%%**********************]  1 of 1 completed
Norway (52, 6)
[*********************100%%**********************]  1 of 1 completed
Israel (52, 6)
[*********************100%%**********************]  1 of 1 completed
New Zealand (52, 6)
[*********************100%%**********************]  1 of 1 completed
China (52, 6)
[*********************100%%**********************]  1 of 1 completed
Taiwan (51, 6)
[*********************100%%**********************]  1 of 1 completed
India (51, 6)
[*********************100%%**********************]  1 of 1 completed
Korea (51, 6)
[*********************100%%**********************]  1 of 1 completed
Brazil (52, 6)
[*********************100%%**********************]  1 of 1 completed
Saudi Arabia (52, 6)
[*********************100%%**********************]  1 of 1 completed
South Africa (52, 6)
[*********************100%%**********************]  1 of 1 completed
Mexico (52, 6)
[*********************100%%**********************]  1 of 1 completed
Thailand (52, 6)
[*********************100%%**********************]  1 of 1 completed
Indonesia (51, 6)
[*********************100%%**********************]  1 of 1 completed
Malaysia (51, 6)
[*********************100%%**********************]  1 of 1 completed
United Arab Emirates (52, 6)
[*********************100%%**********************]  1 of 1 completed
Qatar (51, 6)
[*********************100%%**********************]  1 of 1 completed
Kuwait (51, 6)
[*********************100%%**********************]  1 of 1 completed
Turkiye (52, 6)
[*********************100%%**********************]  1 of 1 completed
Philippines (51, 6)
[*********************100%%**********************]  1 of 1 completed
Poland (52, 6)
[*********************100%%**********************]  1 of 1 completed
Chile (51, 6)
[*********************100%%**********************]  1 of 1 completed
Peru (51, 6)
[*********************100%%**********************]  1 of 1 completed
Hungary (52, 6)
[*********************100%%**********************]  1 of 1 completed
Czechia (52, 6)
[*********************100%%**********************]  1 of 1 completed
Egypt (51, 6)
[*********************100%%**********************]  1 of 1 completed
Colombia (51, 6)
[*********************100%%**********************]  1 of 1 completed
Argentina (52, 6)
[*********************100%%**********************]  1 of 1 completed
Russia (51, 6)

In [7]:
df

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Denmark,...,Poland,Chile,Greece,Peru,Hungary,Czechia,Egypt,Colombia,Argentina,Russia
2023-10-06,1.054663,156.563004,0.86529,1.44551,NaN,0.96256,NaN,1.65593,NaN,7.45586,...,4.60107,950.330017,NaN,3.9233,387.428009,24.420700,32.460999,4459.500000,369.158112,105.590401
2023-10-09,1.056747,157.615997,0.86466,1.44355,NaN,0.96041,NaN,1.65895,NaN,7.45585,...,4.57700,950.500000,NaN,3.9561,386.834015,24.472500,32.359402,4540.600098,369.385498,104.500000
2023-10-10,1.057888,156.909149,0.86353,1.43658,NaN,0.95730,NaN,1.64755,NaN,7.45576,...,4.55900,958.260010,NaN,3.9500,388.453003,24.445400,32.660999,4494.399902,370.283508,105.404297
2023-10-11,1.060479,157.598999,0.86283,1.44039,NaN,0.95925,NaN,1.64861,NaN,7.45535,...,4.53489,959.419983,NaN,3.9867,387.278015,24.548300,32.748001,4522.700195,371.216797,101.319801
2023-10-12,1.062428,158.328995,0.86249,1.44418,NaN,0.95721,NaN,1.65517,NaN,7.45689,...,4.52543,970.130005,NaN,3.9712,386.187988,24.522699,32.826000,4435.500000,371.913391,103.798698
2023-10-13,1.053674,157.811996,0.86477,1.44168,NaN,0.95648,NaN,1.66797,NaN,7.45640,...,4.53854,968.210022,NaN,3.9779,387.062012,24.645599,32.530998,4428.000000,368.846802,102.960503
2023-10-16,1.052155,157.354996,0.86562,1.43546,NaN,0.94960,NaN,1.66713,NaN,7.45800,...,4.45580,972.590027,NaN,3.9602,387.716003,24.667900,32.350601,4439.299805,368.148804,102.050003
2023-10-17,1.055431,157.863007,0.86414,1.43680,NaN,0.95030,NaN,1.66512,NaN,7.45928,...,4.44853,975.429993,NaN,3.9838,386.127014,24.642900,32.612000,4416.600098,369.466400,102.738701
2023-10-18,1.057306,158.309998,0.86810,1.44341,NaN,0.95161,NaN,1.66166,NaN,7.46074,...,4.41650,984.469971,NaN,3.9941,384.242004,24.640400,32.646000,4425.399902,369.948395,103.679199
2023-10-19,1.053852,157.789001,0.86782,1.44515,NaN,0.94712,NaN,1.66412,NaN,7.46076,...,4.44910,977.210022,NaN,3.9799,383.941010,24.672199,32.562000,4383.500000,368.915009,103.360901
2023-10-20,1.058649,158.548004,0.87209,1.45175,NaN,0.94391,NaN,1.67373,NaN,7.46190,...,4.45081,983.200012,NaN,4.0041,382.372009,24.638000,32.681000,4434.299805,370.424805,102.481300
2023-10-23,1.058997,158.712006,0.87054,1.45128,NaN,0.94588,NaN,1.67540,NaN,7.46075,...,4.45615,980.849976,NaN,4.0177,382.036987,24.609301,32.558399,4467.799805,370.382599,100.000000
2023-10-24,1.066985,159.789993,0.87090,1.46045,NaN,0.95042,NaN,1.68375,NaN,7.46251,...,4.45863,987.729980,NaN,4.0378,381.433014,24.599501,32.939999,4442.100098,373.438904,100.823799
2023-10-25,1.059535,158.764008,0.87113,1.45588,NaN,0.94617,NaN,1.66581,NaN,7.46359,...,4.46234,977.890015,NaN,4.0285,382.946991,24.591101,32.737000,4443.299805,370.785309,99.020599
2023-10-26,1.056725,158.598999,0.87301,1.45850,NaN,0.94745,NaN,1.67862,NaN,7.46266,...,4.47464,968.460022,NaN,4.0066,384.407013,24.681499,32.625999,4407.100098,369.851196,99.314697
2023-10-27,1.056446,158.841995,0.87041,1.45950,NaN,0.94952,NaN,1.66791,NaN,7.46346,...,4.44978,961.280029,NaN,4.0051,382.557007,24.639200,32.619999,4356.799805,369.562805,98.927902
2023-10-30,1.056245,158.145996,0.87190,1.46422,NaN,0.95311,NaN,1.66619,NaN,7.46333,...,4.46151,971.669983,NaN,4.0058,383.351990,24.615900,32.467999,4318.899902,369.184692,97.099998
2023-10-31,1.061504,158.261993,0.87240,1.46780,NaN,0.95751,NaN,1.66650,NaN,7.46396,...,4.44430,947.909973,NaN,4.0015,382.421997,24.531300,32.773998,4290.100098,371.476501,98.238403
2023-11-01,1.057910,160.057999,0.87070,1.46790,NaN,0.96244,NaN,1.66880,NaN,7.46370,...,4.45230,946.229980,NaN,3.9949,382.348999,24.553101,32.688000,4285.100098,370.223602,98.720802
2023-11-02,1.058705,159.410004,0.86897,1.46453,NaN,0.95866,NaN,1.64840,NaN,7.46400,...,4.46762,929.599976,NaN,3.9700,383.403992,24.657600,32.681000,4296.000000,370.494812,97.875603
2023-11-03,1.061909,159.753998,0.87077,1.45931,NaN,0.96188,NaN,1.65155,NaN,7.46312,...,4.44627,929.590027,NaN,3.9826,381.700989,24.446800,32.778000,4290.899902,371.603302,99.071297
2023-11-06,1.073215,160.382004,0.86733,1.46594,NaN,0.96490,NaN,1.64686,NaN,7.46075,...,4.45090,933.530029,NaN,3.9365,377.309998,24.362000,32.749199,4232.700195,372.632599,98.750000
2023-11-07,1.072156,160.755005,0.86810,1.46760,NaN,0.96382,NaN,1.65166,NaN,7.45830,...,4.45552,927.109985,NaN,3.9515,378.898010,24.531601,33.095001,4227.000000,375.167999,99.289497
2023-11-08,1.069610,160.852005,0.87008,1.47261,NaN,0.96260,NaN,1.66337,NaN,7.45778,...,4.45335,930.809998,NaN,3.9345,377.903015,24.606899,32.921001,4197.200195,374.225311,98.509804
2023-11-09,1.071042,161.567993,0.87174,1.47721,NaN,0.96292,NaN,1.67130,NaN,7.45768,...,4.43740,935.989990,NaN,3.9566,378.802002,24.600000,33.067001,4234.000000,374.815186,98.354103
2023-11-10,1.066758,161.432007,0.87304,1.47298,NaN,0.96344,NaN,1.67680,NaN,7.45676,...,4.42964,951.580017,NaN,3.9817,378.467010,24.524900,32.933998,4327.500000,373.310303,97.789497
2023-11-13,1.069016,161.910995,0.87416,1.47502,NaN,0.96417,NaN,1.67949,NaN,7.45613,...,4.42039,966.150024,NaN,3.9788,376.696991,24.475401,32.841900,4266.899902,373.588287,97.900002
2023-11-14,1.070183,162.270004,0.87133,1.47687,NaN,0.96446,NaN,1.67728,NaN,7.45779,...,4.42456,961.159973,NaN,3.9684,376.816010,24.544300,33.042000,4257.000000,374.514191,98.330002
2023-11-15,1.087831,163.688995,0.87060,1.49014,NaN,0.96716,NaN,1.67381,NaN,7.45855,...,4.39676,974.159973,NaN,4.0060,375.514008,24.438299,33.597000,4264.600098,380.852600,98.480003
2023-11-16,1.085458,164.130005,0.87375,1.48514,NaN,0.96287,NaN,1.66694,NaN,7.45824,...,4.38640,950.599976,NaN,4.0566,376.328003,24.440599,33.535999,4255.200195,382.953491,97.042999
2023-11-17,1.085376,163.556000,0.87418,1.49248,NaN,0.96424,NaN,1.67756,NaN,7.45656,...,4.37064,945.700012,NaN,4.0680,376.351013,24.436800,33.541000,4334.799805,383.632507,96.938904
2023-11-20,1.090703,163.533997,0.87572,1.49626,NaN,0.96625,NaN,1.67442,NaN,7.45678,...,4.38204,939.190002,NaN,4.1226,377.673004,24.459600,33.453899,4390.899902,384.035004,95.400002
2023-11-21,1.094595,162.378998,0.87498,1.50199,NaN,0.96795,NaN,1.66819,NaN,7.45483,...,4.34410,951.020020,NaN,4.0330,379.571991,24.498800,33.832001,4420.100098,387.294403,96.869797
2023-11-22,1.091822,161.735992,0.87020,1.49572,NaN,0.96440,NaN,1.66464,NaN,7.45490,...,4.37090,942.859985,NaN,4.0067,380.188995,24.505100,33.710999,4349.799805,388.617004,96.281502
2023-11-23,1.089087,162.729996,0.87174,1.49075,NaN,0.96254,NaN,1.66380,NaN,7.45340,...,4.36180,933.700012,NaN,3.9927,380.902008,24.434999,33.618000,4388.000000,388.134399,96.241501
2023-11-24,1.090631,163.160004,0.87000,1.49337,NaN,0.96446,NaN,1.66215,NaN,7.45461,...,4.36320,936.349976,NaN,4.0002,379.188995,24.352100,33.673000,4389.899902,389.291992,96.249702
2023-11-27,1.094044,163.628006,0.86820,1.49100,NaN,0.96517,NaN,1.66217,NaN,7.45420,...,4.36067,936.520020,NaN,4.0021,378.744995,24.380100,33.575001,4389.799805,389.601105,96.500000
2023-11-28,1.095842,162.639999,0.86731,1.49087,NaN,0.96438,NaN,1.65714,NaN,7.45552,...,4.34393,939.599976,NaN,4.0115,379.334991,24.272200,33.834999,4375.399902,393.358490,97.603500
2023-11-29,1.100594,161.815994,0.86558,1.49240,NaN,0.96510,NaN,1.65260,NaN,7.45386,...,4.31764,942.039978,NaN,3.9999,377.101013,24.230101,33.997002,4308.100098,395.624115,97.693398
2023-11-30,1.097370,161.343002,0.86429,1.49123,NaN,0.95835,NaN,1.65819,NaN,7.45534,...,4.33882,938.429993,NaN,4.0050,377.604004,24.241800,33.937000,4293.799805,395.005096,97.313202
2023-12-01,1.089206,161.192993,0.86220,1.47647,NaN,0.95271,NaN,1.64855,NaN,7.45544,...,4.35037,938.530029,NaN,3.9914,379.957001,24.291300,33.634998,4307.899902,392.642914,97.996300
2023-12-04,1.088815,159.386993,0.85641,1.46858,NaN,0.94489,NaN,1.62917,NaN,7.45401,...,4.32569,931.960022,NaN,3.9968,378.378998,24.267799,33.523300,4326.799805,392.856598,96.500000
2023-12-05,1.083776,159.662994,0.85778,1.46680,NaN,0.94540,NaN,1.63730,NaN,7.45520,...,4.32761,919.159973,NaN,3.9800,379.545013,24.393900,33.490002,4259.600098,392.856598,99.147797
2023-12-06,1.079366,158.854996,0.85695,1.46693,NaN,0.94442,NaN,1.64666,NaN,7.45482,...,4.31949,928.900024,NaN,3.9795,379.467010,24.336901,33.215000,4300.200195,391.866211,99.941902
2023-12-07,1.076670,158.451004,0.85717,1.46325,NaN,0.94162,NaN,1.64335,NaN,7.45527,...,4.32723,931.460022,NaN,3.9770,379.975006,24.278999,33.294998,4259.799805,391.407593,100.049698
2023-12-08,1.079214,155.669006,0.85700,1.46726,NaN,0.94466,NaN,1.63635,NaN,7.45494,...,4.32480,915.570007,NaN,3.9622,381.295990,24.283300,33.316002,4270.600098,392.661591,99.757698
2023-12-11,1.076577,156.076004,0.85744,1.46196,NaN,0.94692,NaN,1.63610,NaN,7.45459,...,4.32546,925.719971,NaN,3.9718,379.878998,24.328699,33.168701,4250.100098,392.320404,97.199997
2023-12-12,1.076658,157.257004,0.85750,1.46170,NaN,0.94540,NaN,1.63940,NaN,7.45490,...,4.33330,926.669983,NaN,3.9492,382.726990,24.382999,33.263000,4241.200195,393.825714,98.093399
2023-12-13,1.079867,156.867996,0.85898,1.46691,NaN,0.94497,NaN,1.64486,NaN,7.45586,...,4.32458,935.119995,NaN,3.9978,381.847992,24.479099,33.369999,4225.399902,395.773407,97.505997
2023-12-14,1.088613,155.380005,0.86212,1.46996,NaN,0.94785,NaN,1.63283,NaN,7.45503,...,4.29601,932.599976,NaN,3.9951,378.855988,24.402201,33.605000,4251.399902,395.773407,97.161499
2023-12-15,1.099360,156.408005,0.86086,1.47382,NaN,0.95326,NaN,1.64014,NaN,7.45530,...,4.30480,932.659973,NaN,4.0684,379.247986,24.382700,33.979000,4289.100098,395.773407,98.415298

In [8]:
# Fill ones for countries in Eurozone
for country in currency_codes:
    if currency_codes[country] == '':
        df[country] = 1

In [9]:
# Fill any missing data and round results
df = df.ffill(limit=1)
df = df.round(4)

In [10]:
# Check for NAs
df.loc[:, df.isna().sum() > 0].isna().sum()

Series([], dtype: float64)

In [11]:
df

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Denmark,...,Poland,Chile,Greece,Peru,Hungary,Czechia,Egypt,Colombia,Argentina,Russia
2023-10-06,1.0547,156.5630,0.8653,1.4455,1,0.9626,1,1.6559,1,7.4559,...,4.6011,950.33,1,3.9233,387.428,24.4207,32.4610,4459.5000,369.1581,105.5904
2023-10-09,1.0567,157.6160,0.8647,1.4435,1,0.9604,1,1.6589,1,7.4559,...,4.5770,950.50,1,3.9561,386.834,24.4725,32.3594,4540.6001,369.3855,104.5000
2023-10-10,1.0579,156.9091,0.8635,1.4366,1,0.9573,1,1.6475,1,7.4558,...,4.5590,958.26,1,3.9500,388.453,24.4454,32.6610,4494.3999,370.2835,105.4043
2023-10-11,1.0605,157.5990,0.8628,1.4404,1,0.9592,1,1.6486,1,7.4553,...,4.5349,959.42,1,3.9867,387.278,24.5483,32.7480,4522.7002,371.2168,101.3198
2023-10-12,1.0624,158.3290,0.8625,1.4442,1,0.9572,1,1.6552,1,7.4569,...,4.5254,970.13,1,3.9712,386.188,24.5227,32.8260,4435.5000,371.9134,103.7987
2023-10-13,1.0537,157.8120,0.8648,1.4417,1,0.9565,1,1.6680,1,7.4564,...,4.5385,968.21,1,3.9779,387.062,24.6456,32.5310,4428.0000,368.8468,102.9605
2023-10-16,1.0522,157.3550,0.8656,1.4355,1,0.9496,1,1.6671,1,7.4580,...,4.4558,972.59,1,3.9602,387.716,24.6679,32.3506,4439.2998,368.1488,102.0500
2023-10-17,1.0554,157.8630,0.8641,1.4368,1,0.9503,1,1.6651,1,7.4593,...,4.4485,975.43,1,3.9838,386.127,24.6429,32.6120,4416.6001,369.4664,102.7387
2023-10-18,1.0573,158.3100,0.8681,1.4434,1,0.9516,1,1.6617,1,7.4607,...,4.4165,984.47,1,3.9941,384.242,24.6404,32.6460,4425.3999,369.9484,103.6792
2023-10-19,1.0539,157.7890,0.8678,1.4452,1,0.9471,1,1.6641,1,7.4608,...,4.4491,977.21,1,3.9799,383.941,24.6722,32.5620,4383.5000,368.9150,103.3609
2023-10-20,1.0586,158.5480,0.8721,1.4518,1,0.9439,1,1.6737,1,7.4619,...,4.4508,983.20,1,4.0041,382.372,24.6380,32.6810,4434.2998,370.4248,102.4813
2023-10-23,1.0590,158.7120,0.8705,1.4513,1,0.9459,1,1.6754,1,7.4608,...,4.4562,980.85,1,4.0177,382.037,24.6093,32.5584,4467.7998,370.3826,100.0000
2023-10-24,1.0670,159.7900,0.8709,1.4605,1,0.9504,1,1.6838,1,7.4625,...,4.4586,987.73,1,4.0378,381.433,24.5995,32.9400,4442.1001,373.4389,100.8238
2023-10-25,1.0595,158.7640,0.8711,1.4559,1,0.9462,1,1.6658,1,7.4636,...,4.4623,977.89,1,4.0285,382.947,24.5911,32.7370,4443.2998,370.7853,99.0206
2023-10-26,1.0567,158.5990,0.8730,1.4585,1,0.9474,1,1.6786,1,7.4627,...,4.4746,968.46,1,4.0066,384.407,24.6815,32.6260,4407.1001,369.8512,99.3147
2023-10-27,1.0564,158.8420,0.8704,1.4595,1,0.9495,1,1.6679,1,7.4635,...,4.4498,961.28,1,4.0051,382.557,24.6392,32.6200,4356.7998,369.5628,98.9279
2023-10-30,1.0562,158.1460,0.8719,1.4642,1,0.9531,1,1.6662,1,7.4633,...,4.4615,971.67,1,4.0058,383.352,24.6159,32.4680,4318.8999,369.1847,97.1000
2023-10-31,1.0615,158.2620,0.8724,1.4678,1,0.9575,1,1.6665,1,7.4640,...,4.4443,947.91,1,4.0015,382.422,24.5313,32.7740,4290.1001,371.4765,98.2384
2023-11-01,1.0579,160.0580,0.8707,1.4679,1,0.9624,1,1.6688,1,7.4637,...,4.4523,946.23,1,3.9949,382.349,24.5531,32.6880,4285.1001,370.2236,98.7208
2023-11-02,1.0587,159.4100,0.8690,1.4645,1,0.9587,1,1.6484,1,7.4640,...,4.4676,929.60,1,3.9700,383.404,24.6576,32.6810,4296.0000,370.4948,97.8756
2023-11-03,1.0619,159.7540,0.8708,1.4593,1,0.9619,1,1.6516,1,7.4631,...,4.4463,929.59,1,3.9826,381.701,24.4468,32.7780,4290.8999,371.6033,99.0713
2023-11-06,1.0732,160.3820,0.8673,1.4659,1,0.9649,1,1.6469,1,7.4608,...,4.4509,933.53,1,3.9365,377.310,24.3620,32.7492,4232.7002,372.6326,98.7500
2023-11-07,1.0722,160.7550,0.8681,1.4676,1,0.9638,1,1.6517,1,7.4583,...,4.4555,927.11,1,3.9515,378.898,24.5316,33.0950,4227.0000,375.1680,99.2895
2023-11-08,1.0696,160.8520,0.8701,1.4726,1,0.9626,1,1.6634,1,7.4578,...,4.4534,930.81,1,3.9345,377.903,24.6069,32.9210,4197.2002,374.2253,98.5098
2023-11-09,1.0710,161.5680,0.8717,1.4772,1,0.9629,1,1.6713,1,7.4577,...,4.4374,935.99,1,3.9566,378.802,24.6000,33.0670,4234.0000,374.8152,98.3541
2023-11-10,1.0668,161.4320,0.8730,1.4730,1,0.9634,1,1.6768,1,7.4568,...,4.4296,951.58,1,3.9817,378.467,24.5249,32.9340,4327.5000,373.3103,97.7895
2023-11-13,1.0690,161.9110,0.8742,1.4750,1,0.9642,1,1.6795,1,7.4561,...,4.4204,966.15,1,3.9788,376.697,24.4754,32.8419,4266.8999,373.5883,97.9000
2023-11-14,1.0702,162.2700,0.8713,1.4769,1,0.9645,1,1.6773,1,7.4578,...,4.4246,961.16,1,3.9684,376.816,24.5443,33.0420,4257.0000,374.5142,98.3300
2023-11-15,1.0878,163.6890,0.8706,1.4901,1,0.9672,1,1.6738,1,7.4585,...,4.3968,974.16,1,4.0060,375.514,24.4383,33.5970,4264.6001,380.8526,98.4800
2023-11-16,1.0855,164.1300,0.8737,1.4851,1,0.9629,1,1.6669,1,7.4582,...,4.3864,950.60,1,4.0566,376.328,24.4406,33.5360,4255.2002,382.9535,97.0430
2023-11-17,1.0854,163.5560,0.8742,1.4925,1,0.9642,1,1.6776,1,7.4566,...,4.3706,945.70,1,4.0680,376.351,24.4368,33.5410,4334.7998,383.6325,96.9389
2023-11-20,1.0907,163.5340,0.8757,1.4963,1,0.9663,1,1.6744,1,7.4568,...,4.3820,939.19,1,4.1226,377.673,24.4596,33.4539,4390.8999,384.0350,95.4000
2023-11-21,1.0946,162.3790,0.8750,1.5020,1,0.9679,1,1.6682,1,7.4548,...,4.3441,951.02,1,4.0330,379.572,24.4988,33.8320,4420.1001,387.2944,96.8698
2023-11-22,1.0918,161.7360,0.8702,1.4957,1,0.9644,1,1.6646,1,7.4549,...,4.3709,942.86,1,4.0067,380.189,24.5051,33.7110,4349.7998,388.6170,96.2815
2023-11-23,1.0891,162.7300,0.8717,1.4907,1,0.9625,1,1.6638,1,7.4534,...,4.3618,933.70,1,3.9927,380.902,24.4350,33.6180,4388.0000,388.1344,96.2415
2023-11-24,1.0906,163.1600,0.8700,1.4934,1,0.9645,1,1.6622,1,7.4546,...,4.3632,936.35,1,4.0002,379.189,24.3521,33.6730,4389.8999,389.2920,96.2497
2023-11-27,1.0940,163.6280,0.8682,1.4910,1,0.9652,1,1.6622,1,7.4542,...,4.3607,936.52,1,4.0021,378.745,24.3801,33.5750,4389.7998,389.6011,96.5000
2023-11-28,1.0958,162.6400,0.8673,1.4909,1,0.9644,1,1.6571,1,7.4555,...,4.3439,939.60,1,4.0115,379.335,24.2722,33.8350,4375.3999,393.3585,97.6035
2023-11-29,1.1006,161.8160,0.8656,1.4924,1,0.9651,1,1.6526,1,7.4539,...,4.3176,942.04,1,3.9999,377.101,24.2301,33.9970,4308.1001,395.6241,97.6934
2023-11-30,1.0974,161.3430,0.8643,1.4912,1,0.9584,1,1.6582,1,7.4553,...,4.3388,938.43,1,4.0050,377.604,24.2418,33.9370,4293.7998,395.0051,97.3132
2023-12-01,1.0892,161.1930,0.8622,1.4765,1,0.9527,1,1.6486,1,7.4554,...,4.3504,938.53,1,3.9914,379.957,24.2913,33.6350,4307.8999,392.6429,97.9963
2023-12-04,1.0888,159.3870,0.8564,1.4686,1,0.9449,1,1.6292,1,7.4540,...,4.3257,931.96,1,3.9968,378.379,24.2678,33.5233,4326.7998,392.8566,96.5000
2023-12-05,1.0838,159.6630,0.8578,1.4668,1,0.9454,1,1.6373,1,7.4552,...,4.3276,919.16,1,3.9800,379.545,24.3939,33.4900,4259.6001,392.8566,99.1478
2023-12-06,1.0794,158.8550,0.8569,1.4669,1,0.9444,1,1.6467,1,7.4548,...,4.3195,928.90,1,3.9795,379.467,24.3369,33.2150,4300.2002,391.8662,99.9419
2023-12-07,1.0767,158.4510,0.8572,1.4633,1,0.9416,1,1.6434,1,7.4553,...,4.3272,931.46,1,3.9770,379.975,24.2790,33.2950,4259.7998,391.4076,100.0497
2023-12-08,1.0792,155.6690,0.8570,1.4673,1,0.9447,1,1.6364,1,7.4549,...,4.3248,915.57,1,3.9622,381.296,24.2833,33.3160,4270.6001,392.6616,99.7577
2023-12-11,1.0766,156.0760,0.8574,1.4620,1,0.9469,1,1.6361,1,7.4546,...,4.3255,925.72,1,3.9718,379.879,24.3287,33.1687,4250.1001,392.3204,97.2000
2023-12-12,1.0767,157.2570,0.8575,1.4617,1,0.9454,1,1.6394,1,7.4549,...,4.3333,926.67,1,3.9492,382.727,24.3830,33.2630,4241.2002,393.8257,98.0934
2023-12-13,1.0799,156.8680,0.8590,1.4669,1,0.9450,1,1.6449,1,7.4559,...,4.3246,935.12,1,3.9978,381.848,24.4791,33.3700,4225.3999,395.7734,97.5060
2023-12-14,1.0886,155.3800,0.8621,1.4700,1,0.9478,1,1.6328,1,7.4550,...,4.2960,932.60,1,3.9951,378.856,24.4022,33.6050,4251.3999,395.7734,97.1615
2023-12-15,1.0994,156.4080,0.8609,1.4738,1,0.9533,1,1.6401,1,7.4553,...,4.3048,932.66,1,4.0684,379.248,24.3827,33.9790,4289.1001,395.7734,98.4153

In [12]:
df_new = pd.concat([historic_data.iloc[:-1], df])
df_new

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Denmark,...,Poland,Chile,Greece,Peru,Hungary,Czechia,Egypt,Colombia,Argentina,Russia
1999-01-04,1.1827,132.350,0.7130,1.8060,1,1.6157,1,1.9026,1,7.4508,...,4.0686,NaN,NaN,3.7428,251.410,35.1205,4.0317,1819.5000,NaN,25.3820
1999-01-05,1.1764,131.080,0.7111,1.7794,1,1.6130,1,1.8914,1,7.4392,...,4.0177,NaN,NaN,3.7355,250.605,34.9050,4.0119,1792.5000,NaN,26.7650
1999-01-06,1.1618,131.190,0.7020,1.7554,1,1.6178,1,1.8472,1,7.4472,...,3.9767,NaN,NaN,3.6967,249.700,34.7840,3.9601,1777.5000,NaN,27.0110
1999-01-07,1.1709,130.130,0.7095,1.7725,1,1.6138,1,1.8432,1,7.4490,...,4.0453,NaN,NaN,3.7350,250.430,34.9210,3.9911,1803.0000,NaN,27.1640
1999-01-08,1.1575,128.510,0.7048,1.7509,1,1.6141,1,1.8233,1,7.4443,...,4.0223,NaN,NaN,3.6942,249.540,35.0385,3.9456,1772.0000,NaN,26.9990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-11,1.0766,156.076,0.8574,1.4620,1,0.9469,1,1.6361,1,7.4546,...,4.3255,925.72,1.0,3.9718,379.879,24.3287,33.1687,4250.1001,392.3204,97.2000
2023-12-12,1.0767,157.257,0.8575,1.4617,1,0.9454,1,1.6394,1,7.4549,...,4.3333,926.67,1.0,3.9492,382.727,24.3830,33.2630,4241.2002,393.8257,98.0934
2023-12-13,1.0799,156.868,0.8590,1.4669,1,0.9450,1,1.6449,1,7.4559,...,4.3246,935.12,1.0,3.9978,381.848,24.4791,33.3700,4225.3999,395.7734,97.5060
2023-12-14,1.0886,155.380,0.8621,1.4700,1,0.9478,1,1.6328,1,7.4550,...,4.2960,932.60,1.0,3.9951,378.856,24.4022,33.6050,4251.3999,395.7734,97.1615
2023-12-15,1.0994,156.408,0.8609,1.4738,1,0.9533,1,1.6401,1,7.4553,...,4.3048,932.66,1.0,4.0684,379.248,24.3827,33.9790,4289.1001,395.7734,98.4153

In [13]:
df_new.to_csv('market_data/currency_rates.csv')