In [117]:
import yfinance as yf
import pandas as pd
from datetime import date

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
import time
from io import StringIO

In [128]:
historic_data = pd.read_csv('Stock_Indices.csv', parse_dates=True, index_col=0)
historic_data.tail()

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Denmark,...,Turkiye,Philippines,Poland,Chile,Greece,Hungary,Czechia,Colombia,Argentina,Russia
2023-08-29,4497.629883,32226.970703,7465.000000,20290.400391,7373.430176,11106.240234,15930.879883,7210.500000,745.890015,2193.69,...,7907.100098,6225.000000,2042.08,6059.65,1318.339966,4736.07,1351.70,3590.00,683587.6875,3211.360107
2023-08-30,4514.870117,32333.460938,7473.700195,20330.300781,7364.399902,11090.219727,15891.929688,7297.700195,745.429993,2159.76,...,7907.100098,6295.290039,2049.96,6028.19,1316.939941,4695.35,1359.85,3636.84,675841.0000,3212.679932
2023-08-31,4507.660156,32619.339844,7439.100098,20292.599609,7316.700195,11125.950195,15947.080078,7305.299805,743.619995,2136.82,...,7917.899902,6175.250000,2027.38,6009.28,1312.489990,4650.76,1340.79,3510.86,653602.8750,3227.989990
2023-09-01,4515.770020,32710.619141,7464.500000,20545.400391,7296.770020,11075.150391,15840.339844,7278.299805,746.049988,2170.48,...,8056.100098,6181.060059,2050.94,5996.36,1299.469971,4592.73,1340.71,3528.76,634791.6875,3231.350098
2023-09-04,4515.770020,32939.179688,7452.799805,20545.400391,7279.509766,11053.589844,15824.849609,7318.799805,747.429993,2179.05,...,8141.299805,6214.680176,2025.59,5990.24,1267.329956,4592.88,1336.39,3503.28,633243.3125,3268.969971

In [129]:
start_date = historic_data.last_valid_index()
start_date = str(start_date.date())
start_date

'2023-09-04'

In [130]:
end_date = date.today()
end_date = str(end_date)
end_date

'2023-09-24'

In [118]:
yahoo_references = {
    'United States': '^GSPC',  # S&P 500
    'Japan': '^N225',  # Nikkei 225
    'United Kingdom': '^FTSE',  # FTSE 100
    'Canada': '^GSPTSE',  # S&P/TSX Composite index
    'France': '^FCHI',  # CAC 40
    'Switzerland': '^SSMI',  # SMI PR
    'Germany': '^GDAXI',  # DAX PERFORMANCE-INDEX
    'Australia': '^AXJO',  # S&P/ASX 200
    'Netherlands': '^AEX',  # AEX-Index
    'Denmark': '',
    'Sweden': '^OMX',  # OMX Stockholm 30 Index
    'Spain': '^IBEX',  # IBEX 35
    'Hong Kong': '^HSI',  # HANG SENG INDEX
    'Italy': 'FTSEMIB.MI',  # FTSE MIB Index
    'Singapore': '^STI',  # STI Index
    'Finland': '^OMXH25',  # OMX Helsinki 25
    'Belgium': '^BFX',  # BEL 20
    'Norway': '',
    'Israel': '^TA125.TA',  # TA-125
    'Ireland': '^ISEQ',  # ISEQ All Share
    'New Zealand': '^NZ50',  # S&P/NZX 50 INDEX GROSS
    'Austria': '^ATX',  # Austrian Traded Index
    'Portugal': 'PSI20.LS',  # PSI 20
    'Eurozona': '^STOXX50E',  # Euro Stoxx 50

    'China': '000001.SS',  # SSE Composite Index
    'Taiwan': '^TWII',  # TSEC weighted index
    'India': '^BSESN',  # S&P BSE SENSEX
    'Korea': '^KS11',  # KOSPI Composite Index
    'Brazil': '^BVSP',  # IBOVESPA
    'Saudi Arabia': '^TASI.SR',  # Tadawul All Shares Index
    'South Africa': '',
    'Mexico': '^MXX',  # IPC MEXICO
    'Thailand': '^SET.BK',  # SET Index
    'Indonesia': '^JKSE',  # IDX COMPOSITE
    'Malaysia': '^KLSE',  # FTSE Bursa Malaysia KLCI
    'Turkiye': 'XU100.IS',  # BIST 100
    'Philippines': 'PSEI.PS',  # PSEi INDEX
    'Poland': '',
    'Chile': '',
    'Greece': 'GD.AT',  # COMPOSITE INDEX
    'Hungary': '',
    'Czechia': '',
    'Colombia': '',
    'Argentina': '^MERV',  # MERVAL
    'Russia': 'IMOEX.ME'  # MOEX Russia Index
}

In [122]:
df = pd.DataFrame(index=pd.date_range(start_date, end_date, freq='B'),
                  columns=yahoo_references)

for country in yahoo_references:
    index_ticker = yahoo_references[country]
    if index_ticker != '':
        index_data = yf.download(index_ticker, start_date)
        df[country] = index_data['Adj Close']

df

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Denmark,...,Turkiye,Philippines,Poland,Chile,Greece,Hungary,Czechia,Colombia,Argentina,Russia
2023-09-04,NaN,32939.179688,7452.799805,NaN,7279.509766,11053.589844,15824.849609,7318.799805,747.429993,NaN,...,8141.299805,6214.680176,NaN,NaN,1267.329956,NaN,NaN,NaN,633243.3125,3268.969971
2023-09-05,4496.830078,33036.761719,7437.899902,20413.800781,7254.720215,10958.900391,15771.709961,7314.299805,747.109985,NaN,...,8236.099609,6225.000000,NaN,NaN,1276.520020,NaN,NaN,NaN,598133.3750,3264.429932
2023-09-06,4465.479980,33241.019531,7426.100098,20227.000000,7194.089844,10924.419922,15741.370117,7257.100098,745.429993,NaN,...,8181.700195,6241.689941,NaN,NaN,1273.479980,NaN,NaN,NaN,583982.6250,3245.469971
2023-09-07,4451.140137,32991.078125,7441.700195,20132.099609,7196.100098,10993.429688,15718.660156,7171.000000,739.710022,NaN,...,8337.700195,6183.069824,NaN,NaN,1247.510010,NaN,NaN,NaN,548015.1250,3169.070068
2023-09-08,4457.490234,32606.839844,7478.200195,20074.699219,7240.770020,10948.589844,15740.299805,7156.700195,739.090027,NaN,...,8325.299805,6222.939941,NaN,NaN,1259.500000,NaN,NaN,NaN,532550.3750,3142.879883
2023-09-11,4487.459961,32467.759766,7496.899902,20182.800781,7278.270020,10972.209961,15800.990234,7192.299805,738.890015,NaN,...,8146.500000,6233.740234,NaN,NaN,1250.589966,NaN,NaN,NaN,514073.8125,3122.370117
2023-09-12,4461.899902,32776.371094,7527.500000,20223.099609,7252.879883,10987.129883,15715.530273,7206.899902,736.690002,NaN,...,8159.899902,6230.200195,NaN,NaN,1246.880005,NaN,NaN,NaN,538084.5000,3165.919922
2023-09-13,4467.439941,32706.519531,7526.000000,20278.900391,7222.569824,10976.379883,15654.030273,7153.899902,734.929993,NaN,...,8013.899902,6149.180176,NaN,NaN,1225.250000,NaN,NaN,NaN,553410.1250,3148.320068
2023-09-14,4505.100098,33168.101562,7673.100098,20567.800781,7308.669922,11098.320312,15805.290039,7186.500000,744.460022,NaN,...,8118.799805,6208.399902,NaN,NaN,1233.810059,NaN,NaN,NaN,571753.3125,3139.489990
2023-09-15,4450.319824,33533.089844,7711.399902,20622.300781,7378.819824,11197.719727,15893.530273,7279.000000,741.510010,NaN,...,7962.000000,6126.339844,NaN,NaN,1258.579956,NaN,NaN,NaN,567513.3750,3152.530029
2023-09-18,4453.529785,NaN,7652.899902,20492.800781,7276.140137,11090.610352,15727.120117,7230.399902,735.849976,NaN,...,7680.399902,6124.569824,NaN,NaN,1251.660034,NaN,NaN,NaN,585204.5000,3135.179932
2023-09-19,4443.950195,33242.589844,7660.200195,20218.900391,7282.120117,11068.700195,15664.480469,7196.600098,734.929993,NaN,...,7784.000000,6047.970215,NaN,NaN,1227.780029,NaN,NaN,NaN,576676.1250,3083.850098
2023-09-20,4402.200195,33023.781250,7731.700195,20214.699219,7330.790039,11154.110352,15781.589844,7163.299805,738.320007,NaN,...,7719.799805,6041.040039,NaN,NaN,1200.310059,NaN,NaN,NaN,562032.6250,3068.149902
2023-09-21,4330.000000,32571.029297,7678.600098,19791.599609,7213.899902,11084.740234,15571.860352,7065.200195,731.719971,NaN,...,8000.500000,6094.709961,NaN,NaN,1200.040039,NaN,NaN,NaN,553754.8125,3019.219971
2023-09-22,4320.060059,32402.410156,7683.910156,19779.970703,7184.819824,11014.759766,15557.290039,7068.799805,730.090027,NaN,...,8039.180176,6142.790039,NaN,NaN,1217.750000,NaN,NaN,NaN,NaN,NaN

In [123]:
investing_pages = {
    'Denmark': 'omx-copenhagen-20-historical-data',
    'Norway': 'oslo-obx-historical-data',
    'South Africa': 'ftse-jse-top-40-historical-data',
    'Poland': 'wig-20-historical-data',
    'Chile': 'ipsa-historical-data',
    'Hungary': 'ftse-hungary-historical-data',
    'Czechia': 'px-historical-data',
    'Colombia': 'ftse-colombia-historical-data'
}

In [124]:
def retrieve_prices_from_investing(path):
    service = Service(executable_path='../chromedriver.exe')
    options = webdriver.ChromeOptions()
    driver = webdriver.Chrome(service=service, options=options)

    base_url = 'https://www.investing.com/indices/'
    driver.get(f'{base_url}{path}')
    time.sleep(2)

    botton_cookies = driver.find_element(
        By.XPATH, '//*[@id="onetrust-accept-btn-handler"]'
    )
    botton_cookies.click()
    time.sleep(2)

    table = driver.find_element(
        By.XPATH, '//*[@id="__next"]'
    )
    dfs = pd.read_html(StringIO(table.get_attribute('innerHTML')))
    if path == 'oslo-obx-historical-data':
        df_raw = dfs[1]
    else:
        df_raw = dfs[0]
    driver.close()

    df_raw.index = pd.to_datetime(df_raw['Date'])
    df_raw = df_raw.sort_index()
    return df_raw['Price']

In [125]:
for country in investing_pages:
    path = investing_pages[country]
    df[country] = retrieve_prices_from_investing(path)

df

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Denmark,...,Turkiye,Philippines,Poland,Chile,Greece,Hungary,Czechia,Colombia,Argentina,Russia
2023-09-04,NaN,32939.179688,7452.799805,NaN,7279.509766,11053.589844,15824.849609,7318.799805,747.429993,2179.05,...,8141.299805,6214.680176,2025.59,5990.24,1267.329956,4592.88,1336.39,3503.28,633243.3125,3268.969971
2023-09-05,4496.830078,33036.761719,7437.899902,20413.800781,7254.720215,10958.900391,15771.709961,7314.299805,747.109985,2178.73,...,8236.099609,6225.000000,2006.27,5927.93,1276.520020,4588.84,1337.04,3385.96,598133.3750,3264.429932
2023-09-06,4465.479980,33241.019531,7426.100098,20227.000000,7194.089844,10924.419922,15741.370117,7257.100098,745.429993,2177.63,...,8181.700195,6241.689941,1958.07,5905.74,1273.479980,4612.68,1339.28,3374.85,583982.6250,3245.469971
2023-09-07,4451.140137,32991.078125,7441.700195,20132.099609,7196.100098,10993.429688,15718.660156,7171.000000,739.710022,2194.67,...,8337.700195,6183.069824,1927.39,5885.52,1247.510010,4677.39,1337.14,3398.18,548015.1250,3169.070068
2023-09-08,4457.490234,32606.839844,7478.200195,20074.699219,7240.770020,10948.589844,15740.299805,7156.700195,739.090027,2198.90,...,8325.299805,6222.939941,1943.99,5868.85,1259.500000,4705.90,1321.69,3416.98,532550.3750,3142.879883
2023-09-11,4487.459961,32467.759766,7496.899902,20182.800781,7278.270020,10972.209961,15800.990234,7192.299805,738.890015,2210.07,...,8146.500000,6233.740234,1941.79,5879.15,1250.589966,4740.66,1329.93,3396.73,514073.8125,3122.370117
2023-09-12,4461.899902,32776.371094,7527.500000,20223.099609,7252.879883,10987.129883,15715.530273,7206.899902,736.690002,2198.63,...,8159.899902,6230.200195,1949.57,5886.42,1246.880005,4753.52,1334.28,3528.83,538084.5000,3165.919922
2023-09-13,4467.439941,32706.519531,7526.000000,20278.900391,7222.569824,10976.379883,15654.030273,7153.899902,734.929993,2185.94,...,8013.899902,6149.180176,1949.65,5915.52,1225.250000,4739.71,1338.71,3502.24,553410.1250,3148.320068
2023-09-14,4505.100098,33168.101562,7673.100098,20567.800781,7308.669922,11098.320312,15805.290039,7186.500000,744.460022,2226.84,...,8118.799805,6208.399902,1967.77,6002.07,1233.810059,4778.85,1356.22,3535.02,571753.3125,3139.489990
2023-09-15,4450.319824,33533.089844,7711.399902,20622.300781,7378.819824,11197.719727,15893.530273,7279.000000,741.510010,2190.72,...,7962.000000,6126.339844,1975.05,6002.67,1258.579956,4803.37,1353.96,3644.75,567513.3750,3152.530029
2023-09-18,4453.529785,NaN,7652.899902,20492.800781,7276.140137,11090.610352,15727.120117,7230.399902,735.849976,2153.74,...,7680.399902,6124.569824,1943.94,NaN,1251.660034,4758.40,1351.68,3604.23,585204.5000,3135.179932
2023-09-19,4443.950195,33242.589844,7660.200195,20218.900391,7282.120117,11068.700195,15664.480469,7196.600098,734.929993,2141.79,...,7784.000000,6047.970215,1930.86,NaN,1227.780029,4753.07,1345.53,3641.89,576676.1250,3083.850098
2023-09-20,4402.200195,33023.781250,7731.700195,20214.699219,7330.790039,11154.110352,15781.589844,7163.299805,738.320007,2185.94,...,7719.799805,6041.040039,1975.57,5932.83,1200.310059,4698.19,1349.81,3660.61,562032.6250,3068.149902
2023-09-21,4330.000000,32571.029297,7678.600098,19791.599609,7213.899902,11084.740234,15571.860352,7065.200195,731.719971,2135.60,...,8000.500000,6094.709961,1949.56,5857.72,1200.040039,4513.19,1347.35,3589.38,553754.8125,3019.219971
2023-09-22,4320.060059,32402.410156,7683.910156,19779.970703,7184.819824,11014.759766,15557.290039,7068.799805,730.090027,2129.09,...,8039.180176,6142.790039,1949.25,5831.95,1217.750000,4480.49,1345.55,3541.68,NaN,NaN

In [126]:
df = df.ffill()
df = df.bfill()
df

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Denmark,...,Turkiye,Philippines,Poland,Chile,Greece,Hungary,Czechia,Colombia,Argentina,Russia
2023-09-04,4496.830078,32939.179688,7452.799805,20413.800781,7279.509766,11053.589844,15824.849609,7318.799805,747.429993,2179.05,...,8141.299805,6214.680176,2025.59,5990.24,1267.329956,4592.88,1336.39,3503.28,633243.3125,3268.969971
2023-09-05,4496.830078,33036.761719,7437.899902,20413.800781,7254.720215,10958.900391,15771.709961,7314.299805,747.109985,2178.73,...,8236.099609,6225.000000,2006.27,5927.93,1276.520020,4588.84,1337.04,3385.96,598133.3750,3264.429932
2023-09-06,4465.479980,33241.019531,7426.100098,20227.000000,7194.089844,10924.419922,15741.370117,7257.100098,745.429993,2177.63,...,8181.700195,6241.689941,1958.07,5905.74,1273.479980,4612.68,1339.28,3374.85,583982.6250,3245.469971
2023-09-07,4451.140137,32991.078125,7441.700195,20132.099609,7196.100098,10993.429688,15718.660156,7171.000000,739.710022,2194.67,...,8337.700195,6183.069824,1927.39,5885.52,1247.510010,4677.39,1337.14,3398.18,548015.1250,3169.070068
2023-09-08,4457.490234,32606.839844,7478.200195,20074.699219,7240.770020,10948.589844,15740.299805,7156.700195,739.090027,2198.90,...,8325.299805,6222.939941,1943.99,5868.85,1259.500000,4705.90,1321.69,3416.98,532550.3750,3142.879883
2023-09-11,4487.459961,32467.759766,7496.899902,20182.800781,7278.270020,10972.209961,15800.990234,7192.299805,738.890015,2210.07,...,8146.500000,6233.740234,1941.79,5879.15,1250.589966,4740.66,1329.93,3396.73,514073.8125,3122.370117
2023-09-12,4461.899902,32776.371094,7527.500000,20223.099609,7252.879883,10987.129883,15715.530273,7206.899902,736.690002,2198.63,...,8159.899902,6230.200195,1949.57,5886.42,1246.880005,4753.52,1334.28,3528.83,538084.5000,3165.919922
2023-09-13,4467.439941,32706.519531,7526.000000,20278.900391,7222.569824,10976.379883,15654.030273,7153.899902,734.929993,2185.94,...,8013.899902,6149.180176,1949.65,5915.52,1225.250000,4739.71,1338.71,3502.24,553410.1250,3148.320068
2023-09-14,4505.100098,33168.101562,7673.100098,20567.800781,7308.669922,11098.320312,15805.290039,7186.500000,744.460022,2226.84,...,8118.799805,6208.399902,1967.77,6002.07,1233.810059,4778.85,1356.22,3535.02,571753.3125,3139.489990
2023-09-15,4450.319824,33533.089844,7711.399902,20622.300781,7378.819824,11197.719727,15893.530273,7279.000000,741.510010,2190.72,...,7962.000000,6126.339844,1975.05,6002.67,1258.579956,4803.37,1353.96,3644.75,567513.3750,3152.530029
2023-09-18,4453.529785,33533.089844,7652.899902,20492.800781,7276.140137,11090.610352,15727.120117,7230.399902,735.849976,2153.74,...,7680.399902,6124.569824,1943.94,6002.67,1251.660034,4758.40,1351.68,3604.23,585204.5000,3135.179932
2023-09-19,4443.950195,33242.589844,7660.200195,20218.900391,7282.120117,11068.700195,15664.480469,7196.600098,734.929993,2141.79,...,7784.000000,6047.970215,1930.86,6002.67,1227.780029,4753.07,1345.53,3641.89,576676.1250,3083.850098
2023-09-20,4402.200195,33023.781250,7731.700195,20214.699219,7330.790039,11154.110352,15781.589844,7163.299805,738.320007,2185.94,...,7719.799805,6041.040039,1975.57,5932.83,1200.310059,4698.19,1349.81,3660.61,562032.6250,3068.149902
2023-09-21,4330.000000,32571.029297,7678.600098,19791.599609,7213.899902,11084.740234,15571.860352,7065.200195,731.719971,2135.60,...,8000.500000,6094.709961,1949.56,5857.72,1200.040039,4513.19,1347.35,3589.38,553754.8125,3019.219971
2023-09-22,4320.060059,32402.410156,7683.910156,19779.970703,7184.819824,11014.759766,15557.290039,7068.799805,730.090027,2129.09,...,8039.180176,6142.790039,1949.25,5831.95,1217.750000,4480.49,1345.55,3541.68,553754.8125,3019.219971

In [ ]:
df_new = pd.concat([historic_data, df])
df_new.to_csv('Stock_Indices.csv')