In [4]:
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np

from dotenv import load_dotenv
load_dotenv()

from DataProvider import DataProvider
data_provider = DataProvider()

### Central Bank Rate (BIS)

In [5]:
df_central_bank_rates = data_provider.get_key_indicator_values('Central Bank Rate')
df_central_bank_rates

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
1999-01-01,4.750,0.25,6.25,5.00,3.00,1.00,3.00,4.75,3.00,3.40,6.25,3.00,3.00,15.43,3.95,3.00,3.00,8.00,6.39,15.58,9.0,4.75,29.00,60.0,19.311,32.17,7.0
1999-02-01,4.750,0.25,6.00,5.00,3.00,1.00,3.00,4.75,3.00,3.40,6.25,3.00,3.00,15.02,3.75,3.00,3.00,7.50,6.39,15.58,9.0,4.75,25.00,60.0,18.734,34.12,7.0
1999-03-01,4.750,0.25,5.50,5.00,3.00,1.00,3.00,4.75,3.00,3.15,6.25,3.00,3.00,13.75,3.40,3.00,3.00,7.50,6.39,15.58,9.0,4.75,25.00,60.0,17.304,27.77,7.0
1999-04-01,4.750,0.25,5.50,4.75,3.00,1.00,3.00,4.75,3.00,2.90,6.25,3.00,3.00,16.14,3.40,3.00,3.00,7.00,6.39,15.53,8.0,4.75,42.00,60.0,16.456,22.96,7.0
1999-05-01,4.750,0.25,5.25,4.75,2.50,0.50,2.50,4.75,2.50,2.90,6.25,2.50,2.50,13.60,2.90,2.50,2.50,6.50,6.39,15.53,8.0,4.75,32.00,60.0,15.665,20.24,6.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-01,5.375,-0.10,5.00,5.00,4.00,1.75,4.00,4.10,4.00,3.75,5.75,4.00,4.00,4.22,3.35,4.00,4.00,3.75,3.55,4.20,6.5,3.50,13.75,8.5,8.250,11.25,3.0
2023-09-01,5.375,-0.10,5.25,5.00,4.25,1.75,4.25,4.10,4.25,3.75,5.75,4.25,4.25,4.37,3.35,4.25,4.25,4.00,3.45,4.22,6.5,3.50,13.25,12.0,8.250,11.25,3.0
2023-10-01,5.375,-0.10,5.25,5.00,4.50,1.75,4.50,4.10,4.50,4.00,5.75,4.50,4.50,4.67,3.60,4.50,4.50,4.25,3.45,4.40,6.5,3.50,12.75,13.0,8.250,11.25,3.0
2023-11-01,5.375,-0.10,5.25,5.00,4.50,1.75,4.50,4.10,4.50,4.00,5.75,4.50,4.50,4.67,3.60,4.50,4.50,4.25,3.45,4.40,6.5,3.50,12.75,15.0,8.250,11.25,3.0
2023-12-01,5.375,-0.10,5.25,5.00,4.50,1.75,4.50,4.35,4.50,4.00,5.75,4.50,4.50,4.72,3.60,4.50,4.50,4.25,3.45,4.92,6.5,3.50,12.25,15.0,8.250,11.25,3.0

Indicator provided with just a few days of delay

In [6]:
data_provider.get_latest_data('Central Bank Rate', df_central_bank_rates, 
                              pd.to_datetime('2023-12-05'), 6)

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
2023-07-01,5.125,-0.1,5.00,4.75,4.00,1.75,4.00,4.10,4.00,3.50,5.50,4.00,4.00,4.02,3.10,4.00,4.00,3.75,3.55,4.15,6.5,3.5,13.75,7.5,8.25,11.25,3.0
2023-08-01,5.375,-0.1,5.00,5.00,4.00,1.75,4.00,4.10,4.00,3.75,5.75,4.00,4.00,4.22,3.35,4.00,4.00,3.75,3.55,4.20,6.5,3.5,13.75,8.5,8.25,11.25,3.0
2023-09-01,5.375,-0.1,5.25,5.00,4.25,1.75,4.25,4.10,4.25,3.75,5.75,4.25,4.25,4.37,3.35,4.25,4.25,4.00,3.45,4.22,6.5,3.5,13.25,12.0,8.25,11.25,3.0
2023-10-01,5.375,-0.1,5.25,5.00,4.50,1.75,4.50,4.10,4.50,4.00,5.75,4.50,4.50,4.67,3.60,4.50,4.50,4.25,3.45,4.40,6.5,3.5,12.75,13.0,8.25,11.25,3.0
2023-11-01,5.375,-0.1,5.25,5.00,4.50,1.75,4.50,4.10,4.50,4.00,5.75,4.50,4.50,4.67,3.60,4.50,4.50,4.25,3.45,4.40,6.5,3.5,12.75,15.0,8.25,11.25,3.0
2023-12-01,5.375,-0.1,5.25,5.00,4.50,1.75,4.50,4.35,4.50,4.00,5.75,4.50,4.50,4.72,3.60,4.50,4.50,4.25,3.45,4.92,6.5,3.5,12.25,15.0,8.25,11.25,3.0

### Short Term Interest Rate

In [7]:
indicator = 'Short Term Interest Rate'
df_oecd_indicator = data_provider.get_key_indicator_values(indicator)
df_oecd_indicator

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
1999-01-01,4.89,3.86,5.92,5.00,3.13,3.69,3.13,4.79,3.13,3.27,10.50,3.13,3.13,10.88,3.89,3.13,3.13,7.72,4.52,11.02,7.35,7.00,12.60,43.90,16.40,35.45,6.72
1999-02-01,4.90,3.84,5.53,5.03,3.09,3.58,3.09,4.77,3.09,3.14,9.59,3.09,3.09,9.98,3.62,3.09,3.09,7.27,6.28,10.49,7.44,6.70,11.59,23.30,15.54,31.35,6.46
1999-03-01,4.91,3.82,5.42,5.06,3.05,3.52,3.05,4.81,3.05,3.13,8.56,3.05,3.05,8.96,3.46,3.05,3.05,6.88,4.40,9.09,6.80,6.56,10.40,21.60,14.62,26.37,6.24
1999-04-01,4.88,3.54,5.32,4.72,2.70,0.91,2.70,4.76,2.70,2.87,7.72,2.70,2.70,8.12,3.16,2.70,2.70,6.55,4.34,8.18,6.41,6.16,9.40,20.60,13.75,22.99,5.84
1999-05-01,4.92,3.46,5.35,4.62,2.58,0.91,2.58,4.86,2.58,2.92,7.74,2.58,2.58,8.15,3.11,2.58,2.58,6.66,4.25,8.18,6.33,6.17,9.37,21.00,13.52,23.26,5.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-01,5.49,-0.00,5.53,5.23,3.78,1.77,3.78,4.15,3.78,3.79,4.54,3.78,3.78,4.14,3.80,3.78,3.78,4.72,2.63,4.18,6.80,3.70,6.23,6.20,8.44,11.50,4.13
2023-09-01,5.46,0.02,5.52,5.23,3.88,1.77,3.88,4.13,3.88,3.83,4.90,3.88,3.88,4.20,3.91,3.88,3.88,4.72,2.64,4.18,6.84,3.76,5.87,6.19,8.32,11.51,4.18
2023-10-01,5.41,-0.01,5.40,5.32,3.97,1.77,3.97,4.21,3.97,3.96,4.69,3.97,3.97,4.57,3.97,3.97,3.97,4.72,2.73,4.28,6.89,3.82,5.77,6.27,8.55,11.51,4.57
2023-11-01,5.32,0.02,5.36,5.24,3.97,1.73,3.97,4.38,3.97,4.10,5.02,3.97,3.97,4.58,3.95,3.97,3.97,4.69,2.88,4.29,6.93,3.83,6.09,6.28,8.51,11.51,5.19
2023-12-01,5.26,0.05,5.34,5.19,3.93,1.65,3.93,4.35,3.93,4.03,5.02,3.93,3.93,4.55,3.91,3.93,3.93,4.73,3.02,4.92,6.95,3.83,6.06,6.31,8.45,11.50,5.15

Indicator provided with 2 months delay

In [8]:
data_provider.get_latest_data(indicator, df_oecd_indicator, 
                              pd.to_datetime('2023-12-05'), 6)

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
2023-05-01,5.22,-0.02,4.73,4.79,3.37,1.45,3.37,3.90,3.37,3.50,4.39,3.37,3.37,3.85,3.40,3.37,3.37,3.94,2.98,3.90,6.87,3.64,5.79,3.68,8.04,11.59,3.76
2023-06-01,5.35,-0.00,5.09,5.02,3.54,1.45,3.54,4.25,3.54,3.54,4.57,3.54,3.54,3.98,3.56,3.54,3.54,4.37,2.81,4.09,6.76,3.75,6.05,3.87,8.49,11.51,3.98
2023-07-01,5.44,-0.00,5.49,5.22,3.67,1.72,3.67,4.30,3.67,3.71,4.57,3.67,3.67,3.80,3.72,3.67,3.67,4.68,2.57,4.17,6.72,3.75,6.24,4.03,8.57,11.50,4.12
2023-08-01,5.49,-0.00,5.53,5.23,3.78,1.77,3.78,4.15,3.78,3.79,4.54,3.78,3.78,4.14,3.80,3.78,3.78,4.72,2.63,4.18,6.80,3.70,6.23,6.20,8.44,11.50,4.13
2023-09-01,5.46,0.02,5.52,5.23,3.88,1.77,3.88,4.13,3.88,3.83,4.90,3.88,3.88,4.20,3.91,3.88,3.88,4.72,2.64,4.18,6.84,3.76,5.87,6.19,8.32,11.51,4.18
2023-10-01,5.41,-0.01,5.40,5.32,3.97,1.77,3.97,4.21,3.97,3.96,4.69,3.97,3.97,4.57,3.97,3.97,3.97,4.72,2.73,4.28,6.89,3.82,5.77,6.27,8.55,11.51,4.57

### Long Term Interest Rate

In [9]:
indicator = 'Long Term Interest Rate'
df_oecd_indicator = data_provider.get_key_indicator_values(indicator)
df_oecd_indicator

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
1999-01-01,4.72,1.91,4.29,4.95,3.77,2.56,3.70,5.13,3.80,4.02,5.89,3.88,3.92,6.11,4.04,3.91,3.90,5.01,8.02,5.67,6.33,8.32,12.84,96.34,15.89,6.08,6.55
1999-02-01,5.00,2.12,4.43,5.12,3.93,2.55,3.85,5.30,3.93,4.18,6.03,4.02,4.05,6.26,4.19,4.04,4.04,4.75,7.79,5.83,6.18,8.12,12.84,99.47,14.88,6.22,6.47
1999-03-01,5.23,1.82,4.66,5.22,4.13,2.60,4.04,5.53,4.14,4.44,6.21,4.25,4.27,6.42,4.43,4.26,4.26,4.92,7.81,5.88,6.15,8.17,12.84,98.67,14.54,6.40,6.55
1999-04-01,5.18,1.56,4.59,5.03,3.98,2.53,3.85,5.36,4.00,4.24,6.24,4.09,4.11,6.45,4.22,4.07,4.11,4.69,7.86,5.87,5.99,8.19,13.48,110.55,14.58,6.42,6.43
1999-05-01,5.54,1.33,4.91,5.36,4.16,2.72,4.01,5.88,4.19,4.50,6.44,4.27,4.28,6.69,4.46,4.24,4.29,4.98,8.10,6.00,6.21,8.45,13.48,96.75,15.14,6.67,6.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-01,4.17,0.64,4.53,3.65,3.11,0.95,2.55,4.13,2.92,2.75,4.89,3.59,4.22,3.27,2.77,3.15,3.22,3.81,2.56,3.38,7.19,3.86,7.00,5.78,11.72,9.10,3.28
2023-09-01,4.38,0.76,4.42,3.82,3.24,1.09,2.66,4.21,3.04,2.89,5.39,3.72,4.51,3.39,2.83,3.25,3.32,3.82,2.68,3.62,7.17,3.95,7.00,5.89,12.06,9.68,3.39
2023-10-01,4.80,0.95,4.57,4.06,3.45,1.05,2.82,4.63,3.21,3.02,5.29,3.95,4.88,3.91,3.05,3.47,3.52,3.95,2.69,3.70,7.35,4.27,6.55,5.97,12.36,9.68,3.43
2023-11-01,4.50,0.66,4.27,3.71,3.19,0.82,2.60,4.58,2.95,2.76,5.36,3.66,4.43,4.04,2.79,3.20,3.23,3.68,2.67,3.48,7.27,3.89,6.55,5.69,11.79,10.23,5.51
2023-12-01,4.02,0.62,3.86,3.23,2.65,0.66,2.10,4.19,2.42,2.21,4.83,3.14,3.82,3.55,2.28,2.68,2.70,3.29,2.56,4.60,7.22,3.42,6.55,5.34,11.49,9.39,5.09

Indicator provided with 2 months delay

In [10]:
data_provider.get_latest_data(indicator, df_oecd_indicator, 
                              pd.to_datetime('2023-12-05'), 6)

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
2023-05-01,3.57,0.43,3.96,3.05,2.94,0.85,2.34,3.50,2.73,2.32,5.02,3.41,4.31,3.02,2.54,2.98,3.04,3.23,2.69,3.02,7.01,3.40,7.28,3.56,11.94,8.76,2.54
2023-06-01,3.75,0.40,4.37,3.34,2.93,0.97,2.38,3.92,2.75,2.46,4.91,3.40,4.07,3.06,2.57,3.00,3.05,3.48,2.64,3.15,7.05,3.61,7.28,3.56,11.94,8.57,3.08
2023-07-01,3.90,0.60,4.44,3.45,3.04,0.98,2.46,4.04,2.84,2.52,4.94,3.50,4.16,3.31,2.70,3.07,3.14,3.64,2.66,3.26,7.11,3.68,7.00,3.62,11.72,8.57,3.17
2023-08-01,4.17,0.64,4.53,3.65,3.11,0.95,2.55,4.13,2.92,2.75,4.89,3.59,4.22,3.27,2.77,3.15,3.22,3.81,2.56,3.38,7.19,3.86,7.00,5.78,11.72,9.10,3.28
2023-09-01,4.38,0.76,4.42,3.82,3.24,1.09,2.66,4.21,3.04,2.89,5.39,3.72,4.51,3.39,2.83,3.25,3.32,3.82,2.68,3.62,7.17,3.95,7.00,5.89,12.06,9.68,3.39
2023-10-01,4.80,0.95,4.57,4.06,3.45,1.05,2.82,4.63,3.21,3.02,5.29,3.95,4.88,3.91,3.05,3.47,3.52,3.95,2.69,3.70,7.35,4.27,6.55,5.97,12.36,9.68,3.43

### Total Manufacturing

In [11]:
indicator = 'Total Manufacturing'
df_oecd_indicator = data_provider.get_key_indicator_values(indicator)
df_oecd_indicator

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
1999-01-01,90.62,99.88,75.02,101.95,104.42,92.40,76.31,96.23,81.59,94.74,90.32,121.74,124.59,91.68,89.01,85.1,64.34,91.24,74.80,79.94,34.93,36.50,82.27,47.48,82.42,79.12,92.06
1999-02-01,91.40,99.88,74.91,102.07,103.02,91.62,74.81,95.68,79.30,96.83,90.10,121.69,123.39,91.46,87.34,85.6,63.32,91.32,74.21,80.18,34.63,38.16,81.24,44.83,81.02,79.55,91.24
1999-03-01,91.40,101.60,75.76,101.74,103.44,91.98,75.21,95.57,81.85,97.98,90.27,120.29,123.49,91.45,89.20,86.4,65.14,94.04,75.18,80.57,34.57,38.80,81.21,45.22,80.02,79.48,91.24
1999-04-01,91.72,99.67,75.33,102.72,104.52,92.49,75.71,96.48,80.01,95.89,90.89,123.28,122.99,92.67,83.81,86.7,65.14,89.54,74.37,81.05,35.08,38.43,82.56,44.94,81.32,81.85,91.61
1999-05-01,92.45,101.38,76.28,102.18,105.12,92.53,76.31,96.79,80.62,96.93,91.22,122.45,122.29,92.97,86.87,86.8,65.31,89.96,75.83,81.84,36.09,40.56,84.49,44.65,83.52,80.59,92.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-01,99.25,93.37,107.28,103.46,100.40,138.40,95.56,102.04,109.68,121.20,102.69,106.25,103.49,102.52,151.60,117.6,116.81,100.60,107.10,103.92,129.17,114.71,96.15,109.01,93.11,111.91,108.20
2023-09-01,99.39,93.46,106.86,103.83,99.74,142.40,93.96,101.58,108.78,120.60,104.99,108.37,103.49,102.63,150.40,117.2,116.41,99.33,107.05,104.58,125.86,116.94,95.89,109.01,92.61,113.75,104.65
2023-10-01,98.62,95.82,105.49,103.19,99.94,142.40,93.56,101.07,107.48,120.30,99.80,107.59,103.19,101.07,152.90,116.9,120.31,99.84,101.19,106.49,122.39,112.47,95.87,107.30,92.51,113.24,103.82
2023-11-01,98.93,94.55,105.91,103.19,100.19,142.40,93.16,100.89,106.68,119.30,105.06,107.59,101.99,100.89,168.00,116.5,115.61,99.59,106.56,106.85,124.24,116.20,95.65,108.40,93.21,112.68,107.00
2023-12-01,98.93,94.55,105.91,103.19,100.19,142.40,93.16,100.89,106.68,119.30,108.26,107.59,101.99,100.89,168.00,116.5,115.61,99.59,107.70,110.38,124.24,116.20,95.65,108.40,93.21,112.68,107.00

Indicator provided with 2 months delay

In [12]:
data_provider.get_latest_data(indicator, df_oecd_indicator, 
                              pd.to_datetime('2023-12-05'), 6)

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
2023-05-01,99.55,92.01,105.91,106.01,101.29,135.5,97.17,104.49,112.08,123.6,108.76,107.77,103.79,103.22,155.5,119.4,122.41,100.34,107.84,104.66,125.59,113.22,95.72,114.52,93.21,112.18,105.33
2023-06-01,98.86,96.36,109.27,105.39,100.29,135.6,96.16,104.78,112.78,117.2,106.96,107.00,104.59,106.43,165.4,116.1,117.51,100.34,106.96,103.90,125.22,111.41,95.47,117.41,94.21,112.68,106.14
2023-07-01,99.23,94.09,107.91,104.15,100.74,131.7,94.86,105.67,112.28,118.0,106.16,107.35,103.29,103.06,149.5,116.1,120.91,99.08,106.16,103.21,126.59,108.96,95.09,112.87,92.71,112.83,107.27
2023-08-01,99.25,93.37,107.28,103.46,100.40,138.4,95.56,102.04,109.68,121.2,102.69,106.25,103.49,102.52,151.6,117.6,116.81,100.60,107.10,103.92,129.17,114.71,96.15,109.01,93.11,111.91,108.20
2023-09-01,99.39,93.46,106.86,103.83,99.74,142.4,93.96,101.58,108.78,120.6,104.99,108.37,103.49,102.63,150.4,117.2,116.41,99.33,107.05,104.58,125.86,116.94,95.89,109.01,92.61,113.75,104.65
2023-10-01,98.62,95.82,105.49,103.19,99.94,142.4,93.56,101.07,107.48,120.3,99.80,107.59,103.19,101.07,152.9,116.9,120.31,99.84,101.19,106.49,122.39,112.47,95.87,107.30,92.51,113.24,103.82

### OECD Consumer Confidence Indicator

In [13]:
indicator = 'OECD Consumer Confidence Indicator'
df_oecd_indicator = data_provider.get_key_indicator_values(indicator)
df_oecd_indicator

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
1999-01-01,102.14,99.14,101.75,100.96,101.26,101.19,100.61,101.25,100.97,100.06,101.04,103.74,102.67,101.17,99.29,100.87,100.99,99.96,98.67,99.56,99.40,99.29,98.03,90.73,99.04,101.07,100.64
1999-02-01,102.35,99.23,102.10,101.07,101.22,101.02,100.50,101.55,100.89,100.04,100.98,103.61,102.41,101.12,99.37,100.83,101.02,99.97,98.76,99.52,99.53,99.65,97.54,91.17,99.19,101.01,100.69
1999-03-01,102.38,99.26,102.39,101.10,101.10,100.90,100.29,101.57,100.87,100.11,100.82,103.44,101.99,100.98,99.54,100.97,100.95,99.97,98.79,99.42,99.67,100.01,97.06,91.50,99.33,100.82,100.65
1999-04-01,102.38,99.28,102.50,101.08,101.01,100.84,100.06,101.55,100.97,100.28,100.71,103.30,101.66,100.90,99.69,101.23,100.82,100.01,98.85,99.43,99.85,100.41,96.93,91.72,99.46,100.71,100.59
1999-05-01,102.42,99.34,102.51,101.09,101.05,100.86,99.92,101.46,101.10,100.55,100.73,103.28,101.59,100.95,99.87,101.53,100.55,100.09,98.97,99.59,100.05,100.85,97.20,91.87,99.55,100.74,100.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-01,97.96,98.46,97.84,98.28,98.36,96.93,98.71,97.75,98.44,95.73,97.35,99.11,99.49,98.55,98.82,97.33,99.61,98.15,93.06,98.61,98.57,100.21,101.51,99.61,97.31,105.04,98.49
2023-09-01,97.78,98.35,97.91,98.19,98.24,96.56,98.58,97.76,98.50,95.52,97.00,98.51,99.26,98.20,98.70,96.79,99.63,97.99,93.19,98.52,98.50,99.98,101.49,98.39,97.64,105.14,98.61
2023-10-01,97.55,98.36,97.71,98.08,98.25,96.02,98.54,97.80,98.65,95.62,97.21,98.18,99.07,98.27,98.69,96.40,99.75,97.32,93.29,98.46,98.27,99.75,101.28,98.37,97.76,105.15,97.29
2023-11-01,97.52,98.48,97.97,98.19,98.49,95.43,98.58,97.80,98.95,96.02,97.15,98.13,99.17,98.40,98.72,96.22,100.07,97.44,93.28,98.50,98.35,99.66,101.12,98.38,97.76,105.27,97.88
2023-12-01,97.79,98.68,98.35,98.43,98.71,95.43,98.76,97.86,99.32,96.57,97.30,98.21,99.44,98.62,98.69,96.11,100.48,97.67,93.28,98.23,98.94,99.71,101.05,98.45,97.71,105.32,97.95

Indicator provided with 2 months delay

In [14]:
data_provider.get_latest_data(indicator, df_oecd_indicator, 
                              pd.to_datetime('2023-12-05'), 6)

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
2023-05-01,97.26,98.40,97.20,97.67,97.80,96.91,99.01,97.76,98.34,96.03,97.14,98.24,99.76,98.03,98.56,97.61,99.31,98.03,93.48,98.40,98.43,99.64,100.39,99.61,96.50,103.78,98.22
2023-06-01,97.55,98.53,97.66,98.17,98.22,96.99,98.99,97.70,98.31,96.25,97.15,98.95,99.73,98.52,98.83,97.68,99.39,98.20,93.13,98.51,98.56,100.02,100.85,99.61,96.59,104.22,98.18
2023-07-01,97.90,98.56,97.66,98.27,98.41,97.04,98.88,97.73,98.35,96.08,97.25,99.39,99.63,98.60,98.89,97.59,99.54,98.20,93.01,98.62,98.59,100.25,101.27,99.61,96.91,104.71,98.56
2023-08-01,97.96,98.46,97.84,98.28,98.36,96.93,98.71,97.75,98.44,95.73,97.35,99.11,99.49,98.55,98.82,97.33,99.61,98.15,93.06,98.61,98.57,100.21,101.51,99.61,97.31,105.04,98.49
2023-09-01,97.78,98.35,97.91,98.19,98.24,96.56,98.58,97.76,98.50,95.52,97.00,98.51,99.26,98.20,98.70,96.79,99.63,97.99,93.19,98.52,98.50,99.98,101.49,98.39,97.64,105.14,98.61
2023-10-01,97.55,98.36,97.71,98.08,98.25,96.02,98.54,97.80,98.65,95.62,97.21,98.18,99.07,98.27,98.69,96.40,99.75,97.32,93.29,98.46,98.27,99.75,101.28,98.37,97.76,105.15,97.29

### Current Account to GDP

In [15]:
indicator = 'Current Account to GDP'
df_oecd_indicator = data_provider.get_key_indicator_values(indicator)
df_oecd_indicator

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
1999-01-01,-2.59,2.33,-2.82,-0.15,3.76,2.05,-1.99,-5.63,-0.49,3.00,-2.31,-2.31,0.90,-1.37,1.43,1.96,0.90,0.76,0.87,0.80,-0.30,5.99,-5.04,-0.90,1.64,-1.72,-0.48
1999-02-01,-2.59,2.33,-2.82,-0.15,3.76,2.05,-1.99,-5.63,-0.49,3.00,-2.31,-2.31,0.90,-1.37,1.43,1.96,0.90,0.76,0.87,0.80,-0.30,5.99,-5.04,-0.90,1.64,-1.72,-0.48
1999-03-01,-2.59,2.33,-2.82,-0.15,3.76,2.05,-1.99,-5.63,-0.49,3.00,-2.31,-2.31,0.90,-1.37,1.43,1.96,0.90,0.76,0.87,0.80,-0.30,5.99,-5.04,-0.90,1.64,-1.72,-0.48
1999-04-01,-2.85,2.46,-2.16,-0.25,3.55,10.16,-0.79,-5.93,-0.28,3.91,-1.78,-3.25,1.23,-1.21,2.89,6.39,2.72,3.85,1.11,0.67,-0.96,4.35,-4.34,-0.06,-1.01,-1.67,-0.60
1999-05-01,-2.85,2.46,-2.16,-0.25,3.55,10.16,-0.79,-5.93,-0.28,3.91,-1.78,-3.25,1.23,-1.21,2.89,6.39,2.72,3.85,1.11,0.67,-0.96,4.35,-4.34,-0.06,-1.01,-1.67,-0.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-01,-2.90,4.14,-2.51,-0.44,-1.77,10.87,8.45,-0.02,11.28,7.66,0.30,1.88,0.02,1.25,8.24,-1.08,0.39,18.07,1.18,1.19,-0.70,2.17,-1.38,0.25,-0.04,0.81,1.82
2023-09-01,-2.90,4.14,-2.51,-0.44,-1.77,10.87,8.45,-0.02,11.28,7.66,0.16,1.88,0.02,0.74,8.24,-1.08,0.39,18.07,1.18,1.45,-0.70,2.17,-1.38,0.25,-0.04,0.81,1.68
2023-10-01,-2.90,4.14,-2.51,-0.44,-1.77,10.87,8.45,-0.02,11.28,7.66,1.56,1.88,0.02,0.74,8.24,-1.08,0.39,18.07,1.18,3.07,-0.70,2.17,-1.38,0.25,-0.04,0.81,3.27
2023-11-01,-2.90,4.14,-2.51,-0.44,-1.77,10.87,8.45,-0.02,11.28,7.66,-0.63,1.88,0.02,-0.94,8.24,-1.08,0.39,18.07,1.18,3.07,-0.70,2.17,-1.38,0.25,-0.04,0.81,0.12
2023-12-01,-2.90,4.14,-2.51,-0.44,-1.77,10.87,8.45,-0.02,11.28,7.66,0.16,1.88,0.02,-0.94,8.24,-1.08,0.39,18.07,1.18,1.74,-0.70,2.17,-1.38,0.25,-0.04,0.81,0.12

Indicator provided with up to 3 months delay after current quarter ends

In [16]:
data_provider.get_latest_data(indicator, df_oecd_indicator, 
                              pd.to_datetime('2023-12-05'), 6)

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
2023-01-01,-3.2,1.67,-2.38,-0.95,-1.12,8.38,5.32,1.73,11.35,5.68,1.70,5.49,-0.01,2.66,12.57,0.05,-1.60,19.18,2.81,-0.02,-0.79,0.63,-1.01,1.95,-2.33,-2.04,1.68
2023-02-01,-3.2,1.67,-2.38,-0.95,-1.12,8.38,5.32,1.73,11.35,5.68,1.70,5.49,-0.01,-0.06,12.57,0.05,-1.60,19.18,2.81,1.23,-0.79,0.63,-1.01,1.95,-2.33,-2.04,1.33
2023-03-01,-3.2,1.67,-2.38,-0.95,-1.12,8.38,5.32,1.73,11.35,5.68,0.58,5.49,-0.01,0.88,12.57,0.05,-1.60,19.18,2.81,0.71,-0.79,0.63,-1.01,0.53,-2.33,-2.04,1.56
2023-04-01,-3.2,3.94,-3.55,-1.02,-0.08,7.92,6.91,1.20,9.44,5.11,0.13,1.38,-0.04,1.75,10.95,-1.74,-1.82,14.48,1.56,1.13,-1.18,1.75,-1.85,0.49,-2.11,-0.64,1.86
2023-05-01,-3.2,3.94,-3.55,-1.02,-0.08,7.92,6.91,1.20,9.44,5.11,-0.23,1.38,-0.04,0.76,10.95,-1.74,-1.82,14.48,1.56,1.32,-1.18,1.75,-1.85,0.49,-2.11,-0.64,1.86
2023-06-01,-3.2,3.94,-3.55,-1.02,-0.08,7.92,6.91,1.20,9.44,5.11,0.13,1.38,-0.04,2.42,10.95,-1.74,-1.82,14.48,1.56,1.32,-1.18,1.75,-1.85,0.49,-2.11,-0.64,1.05

### Producer Price Index (Growth YoY)

In [17]:
indicator = 'Producer Price Index'
df_investing_indicator = data_provider.get_key_indicator_values(indicator)
df_investing_indicator

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
1999-01-01,-2.38,-2.4,-3.00,-2.88,-3.00,-3.0,-2.3,-2.38,-3.00,-2.48,-2.76,-3.00,-1.7,-2.38,-3.00,-5.51,-2.38,-2.88,-4.9,-2.74,-3.40,-1.7,-2.12,-2.12,-3.00,-2.88,-2.88
1999-02-01,-2.61,-2.2,-3.32,-3.18,-3.32,-2.9,-2.5,-2.61,-3.32,-3.57,-3.01,-3.32,-1.9,-2.61,-3.32,-5.71,-2.61,-3.18,-4.9,-3.26,-4.16,-4.4,-2.91,-2.91,-3.32,-3.18,-3.18
1999-03-01,-2.39,-1.9,-3.09,-2.93,-3.09,-2.7,-2.3,-2.39,-3.09,-3.15,-2.77,-3.09,-1.9,-2.39,-3.09,-5.42,-2.39,-2.93,-4.6,-3.08,-3.87,-4.3,-2.71,-2.71,-3.09,-2.93,-2.93
1999-04-01,-2.12,-1.9,-2.58,-2.42,-2.58,-2.7,-1.7,-2.12,-2.58,-2.62,-2.36,-2.58,-1.7,-2.12,-2.58,-4.19,-2.12,-2.42,-3.9,-2.86,-3.34,-4.1,-2.40,-2.40,-2.58,-2.42,-2.42
1999-05-01,-1.77,-1.7,-2.23,-2.11,-2.23,-2.3,-1.7,-1.77,-2.23,-1.65,-1.99,-2.23,-1.5,-1.77,-2.23,-3.99,-1.77,-2.11,-3.4,-2.32,-2.69,-2.7,-1.85,-1.85,-2.23,-2.11,-2.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-01,1.60,3.2,-7.98,-7.98,-1.30,-0.8,-12.6,3.80,-7.98,-5.90,3.00,-8.40,-12.2,-7.98,-7.98,-8.40,-7.98,-37.40,-3.0,-7.62,-7.98,1.0,-5.80,10.60,4.30,0.10,-6.60
2023-09-01,2.20,2.0,-8.52,-7.92,-1.70,-1.0,-14.7,3.80,-8.52,-4.60,3.00,-10.00,-14.1,-8.52,-8.52,-8.20,-8.52,-29.30,-2.5,-8.06,-7.92,1.3,-4.30,16.70,5.10,0.70,-7.34
2023-10-01,1.30,0.8,-6.64,-6.64,-1.20,-0.9,-11.0,4.10,-6.64,-3.70,2.70,-7.80,-9.5,-6.64,-6.64,-8.10,-6.64,-10.90,-2.6,-6.30,-6.30,0.8,-3.72,21.60,5.80,1.30,-5.74
2023-11-01,0.90,0.3,-6.74,-6.74,0.30,-1.3,-7.9,4.10,-6.74,-4.20,2.70,-7.80,-12.6,-6.74,-6.74,-7.70,-6.74,-15.60,-3.0,-6.36,-5.14,0.6,-5.46,21.90,4.60,1.20,-6.12
2023-12-01,1.00,0.0,-8.20,-8.20,-0.90,-1.1,-8.6,4.10,-8.20,-7.70,2.70,-7.40,-16.0,-7.98,-8.20,-7.60,-8.20,-25.60,-2.7,-4.54,-8.20,1.2,-6.20,19.20,4.00,1.00,-6.56

Indicator provided with 2 months delay

In [18]:
data_provider.get_latest_data(indicator, df_investing_indicator, 
                              pd.to_datetime('2023-12-05'), 6)

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
2023-05-01,1.1,5.1,-2.44,-1.36,3.0,-0.3,1.0,3.9,-2.44,-2.1,-0.2,-4.5,-4.3,-1.36,-2.44,-6.5,-2.44,-23.5,-4.6,-0.38,-1.36,0.6,-0.82,-3.6,7.3,0.1,-0.02
2023-06-01,0.1,4.1,-3.72,-3.72,3.0,-0.6,0.1,3.9,-3.72,-3.1,-0.2,-8.1,-5.5,-2.78,-3.72,-9.5,-3.72,-28.5,-5.4,-1.72,-2.78,-0.2,-2.20,0.0,4.8,-0.9,-1.22
2023-07-01,0.8,3.6,-5.78,-5.78,0.9,-0.6,-6.0,3.8,-5.78,-2.1,3.0,-8.1,-10.2,-5.78,-5.78,-10.0,-5.78,-35.4,-4.4,-5.70,-4.94,-0.2,-4.56,4.1,2.7,-0.8,-5.40
2023-08-01,1.6,3.2,-7.98,-7.98,-1.3,-0.8,-12.6,3.8,-7.98,-5.9,3.0,-8.4,-12.2,-7.98,-7.98,-8.4,-7.98,-37.4,-3.0,-7.62,-7.98,1.0,-5.80,10.6,4.3,0.1,-6.60
2023-09-01,2.2,2.0,-8.52,-7.92,-1.7,-1.0,-14.7,3.8,-8.52,-4.6,3.0,-10.0,-14.1,-8.52,-8.52,-8.2,-8.52,-29.3,-2.5,-8.06,-7.92,1.3,-4.30,16.7,5.1,0.7,-7.34
2023-10-01,1.3,0.8,-6.64,-6.64,-1.2,-0.9,-11.0,4.1,-6.64,-3.7,2.7,-7.8,-9.5,-6.64,-6.64,-8.1,-6.64,-10.9,-2.6,-6.30,-6.30,0.8,-3.72,21.6,5.8,1.3,-5.74

### Industrial Production

In [19]:
indicator = 'Industrial Production'
df_investing_indicator = data_provider.get_indicator_values(
    indicator, 'Investing', 'MS')
df_investing_indicator

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
1999-01-01,NaN,NaN,-0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.7,-0.9,9.9,NaN,NaN,NaN,NaN,17.9,18.23,NaN,16.9,-3.40,NaN,NaN,3.43,-12.3
1999-02-01,NaN,NaN,-0.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.1,-2.3,3.8,NaN,NaN,NaN,NaN,2.1,-5.35,NaN,5.4,-4.91,NaN,NaN,1.32,3.0
1999-03-01,NaN,NaN,-0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.6,-0.5,6.8,NaN,NaN,NaN,NaN,9.0,8.16,NaN,20.7,-2.72,NaN,NaN,1.26,2.8
1999-04-01,NaN,NaN,-1.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.2,-3.1,5.7,NaN,NaN,NaN,NaN,9.1,7.99,NaN,18.8,-2.54,NaN,NaN,1.27,4.3
1999-05-01,NaN,NaN,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.8,-3.7,19.0,NaN,NaN,NaN,NaN,8.9,10.25,NaN,23.9,-3.02,NaN,NaN,0.67,6.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-01,0.25,NaN,1.3,NaN,NaN,NaN,-1.75,NaN,NaN,-4.0,NaN,-3.4,-4.2,-12.1,NaN,NaN,NaN,NaN,4.5,-10.53,10.3,-0.5,0.50,5.4,NaN,5.20,-0.3
2023-09-01,0.08,NaN,1.5,NaN,NaN,NaN,-3.86,NaN,NaN,4.7,NaN,-1.4,-2.0,-2.1,NaN,NaN,NaN,NaN,4.5,-6.72,5.8,3.0,0.60,5.6,NaN,3.90,-0.5
2023-10-01,-0.68,NaN,0.4,NaN,NaN,-0.4,-3.38,NaN,NaN,1.9,4.1,-1.5,-1.1,7.4,NaN,NaN,NaN,NaN,4.6,-2.32,11.7,1.1,1.20,5.3,NaN,5.50,2.7
2023-11-01,-0.39,NaN,-5.1,NaN,NaN,NaN,NaN,NaN,NaN,-1.1,NaN,-1.1,-3.7,1.0,NaN,NaN,NaN,NaN,6.6,-2.48,7.1,5.3,0.90,4.3,NaN,3.20,4.8
2023-12-01,0.98,NaN,-4.0,NaN,NaN,NaN,NaN,NaN,NaN,0.2,NaN,0.6,0.1,-2.5,NaN,NaN,NaN,NaN,6.8,-3.99,4.3,6.2,-1.30,2.7,NaN,3.00,3.0

In [20]:
df_oecd_indicator = data_provider.get_indicator_values(
    indicator, 'OECD', 'MS')
df_oecd_indicator

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
1999-01-01,3.64,-6.21,4.34,5.45,1.42,NaN,0.40,NaN,1.09,1.88,NaN,4.28,-1.62,NaN,1.81,3.46,-0.55,-2.20,NaN,NaN,5.56,10.14,-1.06,-2.24,NaN,NaN,NaN
1999-02-01,4.06,-3.70,3.48,4.07,0.41,NaN,-1.20,NaN,3.19,3.55,NaN,0.54,-2.02,NaN,0.86,2.27,-2.68,-1.76,NaN,NaN,3.56,13.59,-4.39,-9.36,NaN,NaN,NaN
1999-03-01,4.24,-0.32,3.81,2.67,1.54,NaN,-1.85,NaN,3.84,3.74,NaN,0.40,-1.22,NaN,1.05,1.79,-0.31,-2.47,NaN,NaN,4.67,20.40,-3.86,-5.86,NaN,NaN,NaN
1999-04-01,4.12,-1.79,3.10,3.75,1.04,NaN,-0.27,NaN,0.87,0.76,NaN,1.45,-2.74,NaN,0.33,1.66,-0.39,-6.74,NaN,NaN,5.00,20.63,-3.00,-5.77,NaN,NaN,NaN
1999-05-01,4.08,0.53,4.98,4.39,0.17,NaN,-0.13,NaN,-0.21,3.54,NaN,1.08,-3.31,NaN,3.54,2.12,-0.34,-0.56,NaN,NaN,7.44,25.78,-3.14,-1.14,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-01,-0.02,-4.09,1.06,-0.31,-0.38,2.13,-0.31,NaN,-7.62,1.55,NaN,-3.26,-4.31,NaN,4.23,-0.17,-4.50,-8.66,NaN,NaN,NaN,-0.92,0.44,NaN,NaN,NaN,NaN
2023-09-01,-0.18,-3.10,1.17,-0.50,-0.32,2.28,-3.39,NaN,-9.28,-4.00,NaN,-1.36,-2.11,NaN,1.63,-2.58,-11.80,-17.09,NaN,NaN,NaN,2.05,1.82,NaN,NaN,NaN,NaN
2023-10-01,-0.96,-0.66,-0.53,0.46,2.04,NaN,-3.10,NaN,-10.25,-0.26,NaN,-1.54,-1.16,NaN,7.93,0.51,-6.65,-7.96,NaN,NaN,NaN,1.44,0.56,NaN,NaN,NaN,NaN
2023-11-01,-0.39,-1.23,-0.11,NaN,0.64,NaN,-4.51,NaN,-9.72,3.46,NaN,NaN,-2.90,NaN,14.87,1.38,-11.62,-5.57,NaN,NaN,NaN,5.31,1.16,NaN,NaN,NaN,NaN
2023-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df_combined = df_investing_indicator.combine_first(df_oecd_indicator)
df_combined

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
1999-01-01,3.64,-6.21,-0.2,5.45,1.42,NaN,0.40,NaN,1.09,1.88,NaN,4.7,-0.9,9.9,1.81,3.46,-0.55,-2.20,17.9,18.23,5.56,16.9,-3.40,-2.24,NaN,3.43,-12.3
1999-02-01,4.06,-3.70,-0.9,4.07,0.41,NaN,-1.20,NaN,3.19,3.55,NaN,-0.1,-2.3,3.8,0.86,2.27,-2.68,-1.76,2.1,-5.35,3.56,5.4,-4.91,-9.36,NaN,1.32,3.0
1999-03-01,4.24,-0.32,-0.5,2.67,1.54,NaN,-1.85,NaN,3.84,3.74,NaN,0.6,-0.5,6.8,1.05,1.79,-0.31,-2.47,9.0,8.16,4.67,20.7,-2.72,-5.86,NaN,1.26,2.8
1999-04-01,4.12,-1.79,-1.7,3.75,1.04,NaN,-0.27,NaN,0.87,0.76,NaN,1.2,-3.1,5.7,0.33,1.66,-0.39,-6.74,9.1,7.99,5.00,18.8,-2.54,-5.77,NaN,1.27,4.3
1999-05-01,4.08,0.53,0.1,4.39,0.17,NaN,-0.13,NaN,-0.21,3.54,NaN,0.8,-3.7,19.0,3.54,2.12,-0.34,-0.56,8.9,10.25,7.44,23.9,-3.02,-1.14,NaN,0.67,6.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-01,0.25,-4.09,1.3,-0.31,-0.38,2.13,-1.75,NaN,-7.62,-4.00,NaN,-3.4,-4.2,-12.1,4.23,-0.17,-4.50,-8.66,4.5,-10.53,10.30,-0.5,0.50,5.40,NaN,5.20,-0.3
2023-09-01,0.08,-3.10,1.5,-0.50,-0.32,2.28,-3.86,NaN,-9.28,4.70,NaN,-1.4,-2.0,-2.1,1.63,-2.58,-11.80,-17.09,4.5,-6.72,5.80,3.0,0.60,5.60,NaN,3.90,-0.5
2023-10-01,-0.68,-0.66,0.4,0.46,2.04,-0.40,-3.38,NaN,-10.25,1.90,4.1,-1.5,-1.1,7.4,7.93,0.51,-6.65,-7.96,4.6,-2.32,11.70,1.1,1.20,5.30,NaN,5.50,2.7
2023-11-01,-0.39,-1.23,-5.1,NaN,0.64,NaN,-4.51,NaN,-9.72,-1.10,NaN,-1.1,-3.7,1.0,14.87,1.38,-11.62,-5.57,6.6,-2.48,7.10,5.3,0.90,4.30,NaN,3.20,4.8
2023-12-01,0.98,NaN,-4.0,NaN,NaN,NaN,NaN,NaN,NaN,0.20,NaN,0.6,0.1,-2.5,NaN,NaN,NaN,NaN,6.8,-3.99,4.30,6.2,-1.30,2.70,NaN,3.00,3.0

In [22]:
df_combined.isna().sum()

United States       0
Japan               1
United Kingdom      0
Canada              2
France              1
Switzerland       155
Germany             1
Australia         300
Netherlands         1
Sweden              0
Hong Kong         296
Spain               0
Italy               0
Singapore           9
Denmark             1
Finland             1
Belgium             1
Norway              1
China              18
Taiwan              9
India               0
Korea               0
Brazil              0
Russia              0
South Africa      300
Mexico              2
Malaysia            2
dtype: int64

In [23]:
indicator = 'Industrial Production'
df_investing_indicator = data_provider.get_key_indicator_values(indicator)
df_investing_indicator

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
1999-01-01,3.64,-6.21,-0.2,5.45,1.42,0.69,0.40,2.61,1.09,1.88,2.67,4.7,-0.9,9.9,1.81,3.46,-0.55,-2.20,17.9,18.23,5.56,16.9,-3.40,-2.24,0.91,3.43,-12.3
1999-02-01,4.06,-3.70,-0.9,4.07,0.41,-1.44,-1.20,1.51,3.19,3.55,0.67,-0.1,-2.3,3.8,0.86,2.27,-2.68,-1.76,2.1,-5.35,3.56,5.4,-4.91,-9.36,0.68,1.32,3.0
1999-03-01,4.24,-0.32,-0.5,2.67,1.54,-0.51,-1.85,1.84,3.84,3.74,1.82,0.6,-0.5,6.8,1.05,1.79,-0.31,-2.47,9.0,8.16,4.67,20.7,-2.72,-5.86,0.34,1.26,2.8
1999-04-01,4.12,-1.79,-1.7,3.75,1.04,-0.85,-0.27,1.42,0.87,0.76,1.37,1.2,-3.1,5.7,0.33,1.66,-0.39,-6.74,9.1,7.99,5.00,18.8,-2.54,-5.77,-0.82,1.27,4.3
1999-05-01,4.08,0.53,0.1,4.39,0.17,-0.65,-0.13,1.12,-0.21,3.54,4.17,0.8,-3.7,19.0,3.54,2.12,-0.34,-0.56,8.9,10.25,7.44,23.9,-3.02,-1.14,0.72,0.67,6.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-01,0.25,-4.09,1.3,-0.31,-0.38,2.13,-1.75,-1.07,-7.62,-4.00,4.40,-3.4,-4.2,-12.1,4.23,-0.17,-4.50,-8.66,4.5,-10.53,10.30,-0.5,0.50,5.40,-1.72,5.20,-0.3
2023-09-01,0.08,-3.10,1.5,-0.50,-0.32,2.28,-3.86,-1.04,-9.28,4.70,4.40,-1.4,-2.0,-2.1,1.63,-2.58,-11.80,-17.09,4.5,-6.72,5.80,3.0,0.60,5.60,-2.31,3.90,-0.5
2023-10-01,-0.68,-0.66,0.4,0.46,2.04,-0.40,-3.38,-0.32,-10.25,1.90,4.10,-1.5,-1.1,7.4,7.93,0.51,-6.65,-7.96,4.6,-2.32,11.70,1.1,1.20,5.30,-2.46,5.50,2.7
2023-11-01,-0.39,-1.23,-5.1,0.46,0.64,-0.40,-4.51,-2.44,-9.72,-1.10,4.10,-1.1,-3.7,1.0,14.87,1.38,-11.62,-5.57,6.6,-2.48,7.10,5.3,0.90,4.30,-2.14,3.20,4.8
2023-12-01,0.98,-1.23,-4.0,0.46,0.64,-0.40,-4.51,-1.46,-9.72,0.20,4.10,0.6,0.1,-2.5,14.87,1.38,-11.62,-5.57,6.8,-3.99,4.30,6.2,-1.30,2.70,-1.17,3.00,3.0

Indicator provided with 3 months delay

In [24]:
data_provider.get_latest_data(indicator, df_investing_indicator, 
                              pd.to_datetime('2023-12-05'), 6)

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
2023-04-01,0.24,0.19,-1.9,0.15,1.43,-0.80,1.75,-2.05,-11.70,-0.1,2.7,-0.9,-7.2,-6.9,10.25,-3.39,-4.03,-5.59,5.6,-22.86,4.2,-8.9,-2.7,5.2,-2.76,0.7,-3.3
2023-05-01,0.23,2.30,-2.3,0.40,2.23,-0.15,0.82,-1.53,-8.82,3.4,2.7,-0.1,-3.7,-10.8,6.35,0.08,-3.86,-9.63,3.5,-15.73,5.2,-7.3,1.9,7.1,-1.60,3.9,4.7
2023-06-01,-0.43,-0.19,0.7,-0.10,-0.03,-1.80,-1.83,-1.57,-6.59,3.8,2.7,-3.0,-0.8,-4.9,11.48,-5.40,-4.90,-7.89,4.4,-16.63,3.7,-5.6,0.3,6.5,-2.63,3.7,-2.2
2023-07-01,-0.23,-2.26,0.4,0.14,2.49,2.00,-2.25,-1.20,-6.92,-2.8,4.4,-1.8,-2.1,-0.9,4.30,-2.11,-3.50,-6.60,3.7,-15.20,5.7,-8.0,-1.1,4.9,-1.68,4.8,0.7
2023-08-01,0.25,-4.09,1.3,-0.31,-0.38,2.13,-1.75,-1.07,-7.62,-4.0,4.4,-3.4,-4.2,-12.1,4.23,-0.17,-4.50,-8.66,4.5,-10.53,10.3,-0.5,0.5,5.4,-1.72,5.2,-0.3
2023-09-01,0.08,-3.10,1.5,-0.50,-0.32,2.28,-3.86,-1.04,-9.28,4.7,4.4,-1.4,-2.0,-2.1,1.63,-2.58,-11.80,-17.09,4.5,-6.72,5.8,3.0,0.6,5.6,-2.31,3.9,-0.5

### Retail Sales

In [25]:
indicator = 'Retail Sales'
df_investing_indicator = data_provider.get_key_indicator_values(indicator)
df_investing_indicator

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
1999-01-01,-7.12,-0.6,0.8,-4.58,-2.00,-3.62,-2.3,-7.00,0.00,4.2,-20.8,-3.62,-3.62,-12.7,0.42,-3.62,0.42,-3.90,5.9,-5.64,-2.26,-5.64,-7.12,-3.62,-7.00,-7.12,-3.74
1999-02-01,1.98,1.8,0.6,0.64,4.24,1.28,0.9,2.42,4.00,5.0,-4.1,1.28,1.28,10.7,2.46,1.28,2.46,1.52,10.6,4.60,3.46,4.60,1.98,1.28,2.42,1.98,0.84
1999-03-01,2.62,1.8,1.2,0.94,8.68,2.08,4.9,4.40,10.71,7.5,-13.9,2.08,2.08,19.1,5.22,2.08,5.22,2.20,5.8,4.70,2.38,4.70,2.62,2.08,4.40,2.62,0.30
1999-04-01,-3.48,-2.3,0.9,-1.58,0.40,-0.66,-2.7,-1.92,5.49,2.3,-9.3,-0.66,-0.66,-4.0,0.74,-0.66,0.74,-1.30,5.7,-0.88,0.38,-0.88,-3.48,-0.66,-1.92,-3.48,-2.22
1999-05-01,-0.18,-3.5,2.1,-1.89,3.67,-0.01,-2.3,0.93,2.06,5.9,-7.8,-0.01,-0.01,10.6,0.85,-0.01,0.85,-1.13,5.3,1.33,0.39,1.33,-0.18,-0.01,0.93,-0.18,-1.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-01,2.47,7.0,-1.4,1.68,1.68,-1.80,-2.3,1.68,6.80,-1.7,13.7,7.20,2.40,4.0,-1.00,1.68,1.08,1.68,4.6,2.76,1.68,2.76,2.30,11.00,-0.50,3.20,1.08
2023-09-01,3.75,5.8,-1.0,0.02,0.02,-0.60,-4.3,-1.02,3.40,-3.8,13.0,6.50,1.30,0.6,1.30,-1.02,-1.02,0.02,5.5,0.34,0.02,0.34,3.30,12.20,0.90,2.30,0.90
2023-10-01,2.48,4.2,-2.7,-0.00,-0.00,-0.10,-0.1,-0.00,3.90,-1.0,5.6,5.00,0.30,-0.1,3.70,-0.00,-0.00,-0.00,7.6,-0.00,0.86,2.06,0.20,12.70,-2.50,3.40,-0.00
2023-11-01,4.09,5.3,0.1,0.62,0.62,-1.30,-5.9,0.62,3.70,-1.0,-4.2,5.20,4.40,6.2,6.30,0.62,0.62,0.62,10.1,0.44,0.62,2.84,1.50,10.50,0.40,2.40,2.84
2023-12-01,5.59,2.1,-2.4,0.60,0.60,-0.80,-1.7,0.60,1.90,-2.2,1.1,3.10,3.40,7.4,4.50,0.60,0.60,-0.46,7.4,0.60,0.60,2.52,0.40,-10.50,-0.60,2.50,2.26

Indicator provided with 3 months delay

In [26]:
data_provider.get_latest_data(indicator, df_investing_indicator, 
                              pd.to_datetime('2023-12-05'), 6)

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
2023-04-01,1.60,5.0,-3.0,-1.22,-1.22,-3.7,-4.3,-1.22,2.7,-6.5,15.0,5.5,3.2,3.6,-6.0,-1.22,-1.22,-1.22,18.4,0.10,-1.22,0.10,0.5,7.4,-1.6,3.8,0.10
2023-05-01,1.61,5.7,-2.1,0.18,0.18,-1.1,-3.6,0.18,6.3,-5.4,18.4,6.0,3.0,1.8,-0.4,0.18,-0.60,0.18,12.7,0.96,0.18,0.96,-1.0,9.3,-1.4,2.6,0.18
2023-06-01,1.49,5.9,-1.0,1.58,1.58,-1.1,-1.6,1.58,9.0,-4.4,19.6,6.4,3.6,1.1,2.0,1.58,0.62,1.58,3.1,2.00,1.58,2.00,1.3,10.0,-0.9,5.9,1.58
2023-07-01,3.17,6.8,-3.2,0.60,0.60,-2.2,-2.2,0.60,3.7,-2.1,16.5,7.3,2.7,1.1,-5.4,0.60,-0.54,0.60,2.5,1.46,0.60,1.46,2.4,10.5,-1.8,5.1,-0.54
2023-08-01,2.47,7.0,-1.4,1.68,1.68,-1.8,-2.3,1.68,6.8,-1.7,13.7,7.2,2.4,4.0,-1.0,1.68,1.08,1.68,4.6,2.76,1.68,2.76,2.3,11.0,-0.5,3.2,1.08
2023-09-01,3.75,5.8,-1.0,0.02,0.02,-0.6,-4.3,-1.02,3.4,-3.8,13.0,6.5,1.3,0.6,1.3,-1.02,-1.02,0.02,5.5,0.34,0.02,0.34,3.3,12.2,0.9,2.3,0.90

### Historic monthly returns

In [27]:
indicator = 'Monthly Returns'
df_investing_indicator = data_provider.get_key_indicator_values(indicator)
df_investing_indicator

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
Days to rebalance,,,,,,,,,,,,,,,,,,,,,,,,,,,
1999-02-04,0.008503,0.030397,-0.018294,0.020206,-0.061127,-0.057568,-0.065953,0.056789,-0.130889,0.003031,-0.085168,-0.124657,-0.145383,-0.086071,-0.091252,-0.012550,-0.083984,0.007761,-0.238886,-0.059246,0.046924,-0.121434,-0.202463,-0.028192,0.038042,0.000000,0.051293
1999-03-04,-0.003742,-0.068139,0.015267,-0.061868,-0.062062,-0.053245,-0.104733,-0.043882,-0.056999,-0.056095,0.036370,-0.041534,-0.022247,0.043961,-0.100794,-0.014816,-0.108393,-0.069825,0.054117,0.115651,0.103247,-0.071561,-0.043102,0.357561,0.025318,0.047629,-0.182306
1999-04-06,0.057370,0.212835,0.044451,0.081674,0.056309,0.000000,0.034112,0.056081,0.067497,0.065146,0.120956,0.000000,0.048792,0.102117,0.036258,0.135726,-0.016974,0.071234,0.106784,0.146593,-0.010190,0.234229,0.332078,0.169694,0.040133,0.264143,0.215108
1999-05-04,0.012460,0.010310,0.048101,0.075504,0.008608,0.030771,0.050530,0.103526,0.072991,0.017859,0.220612,-0.015749,-0.021663,0.217308,0.069718,-0.051812,-0.013798,0.108272,0.219836,0.059320,-0.020577,0.165162,0.041584,0.166238,0.138565,0.089622,0.573341
1999-06-04,-0.003980,-0.058065,-0.030858,-0.009126,-0.017290,-0.034683,-0.062796,-0.073663,-0.034574,-0.014865,-0.052098,0.009028,-0.047331,-0.064537,-0.050743,-0.002108,-0.038939,-0.099200,-0.004725,-0.030255,0.134927,0.091673,-0.033458,0.150613,-0.036237,-0.071922,-0.189624
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-03,0.020665,0.006888,0.033295,0.018893,0.025460,0.033442,0.027725,0.018979,0.028764,0.013482,0.037524,0.011775,0.042681,0.070731,-0.002874,-0.017829,0.060051,0.080041,0.096570,0.002606,0.000459,0.041172,0.032418,0.000000,0.073976,-0.007650,0.072344
2023-09-06,-0.005854,0.016853,-0.024708,-0.013042,-0.031723,-0.031665,-0.033583,-0.021720,-0.065246,-0.032848,-0.077616,-0.025873,-0.036242,-0.052574,-0.004904,0.005881,-0.028464,-0.021909,-0.066343,-0.012002,0.012989,-0.053830,-0.048542,0.000000,-0.062733,-0.024983,-0.018913
2023-10-05,-0.046379,-0.049409,-0.015316,-0.053938,-0.045259,-0.042839,-0.057439,-0.035859,-0.079612,-0.021591,-0.059796,-0.027682,-0.048325,-0.019824,-0.046263,-0.070439,-0.065390,-0.032229,-0.072243,-0.016379,-0.000226,-0.067359,-0.055477,0.000000,-0.061942,-0.096484,-0.028566
2023-11-03,0.023721,0.045706,0.007368,0.039836,0.018687,0.000232,0.016969,0.033570,0.051160,0.016766,0.028920,0.041421,0.054085,0.016548,0.008345,0.034017,0.044632,0.013371,0.025051,0.020542,-0.000226,0.028731,0.091868,0.000000,0.114365,0.093799,0.041372
2023-12-05,0.049175,0.000323,0.032347,0.038595,0.053255,0.055176,0.092699,0.024010,0.067067,0.100846,-0.071480,0.097755,0.051309,-0.018775,0.057392,0.037008,0.038370,0.011446,-0.055867,0.052386,0.068283,0.030858,0.056078,0.000000,-0.020691,0.063299,-0.003777

Indicator calculated without delay

In [28]:
data_provider.get_latest_data(indicator, df_investing_indicator, 
                              pd.to_datetime('2023-12-05'), 6)

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
Days to rebalance,,,,,,,,,,,,,,,,,,,,,,,,,,,
2023-07-06,0.030516,-0.029813,-0.022985,-0.003047,0.002636,-0.025652,-0.013094,-0.016425,0.004232,-0.032799,-0.038904,0.012715,0.030632,-0.028464,-0.012310,-0.041619,-0.016877,0.015122,-0.035090,-0.027458,0.032652,-0.044985,0.021535,0.0,-0.017955,-0.004239,-0.015241
2023-08-03,0.020665,0.006888,0.033295,0.018893,0.025460,0.033442,0.027725,0.018979,0.028764,0.013482,0.037524,0.011775,0.042681,0.070731,-0.002874,-0.017829,0.060051,0.080041,0.096570,0.002606,0.000459,0.041172,0.032418,0.0,0.073976,-0.007650,0.072344
2023-09-06,-0.005854,0.016853,-0.024708,-0.013042,-0.031723,-0.031665,-0.033583,-0.021720,-0.065246,-0.032848,-0.077616,-0.025873,-0.036242,-0.052574,-0.004904,0.005881,-0.028464,-0.021909,-0.066343,-0.012002,0.012989,-0.053830,-0.048542,0.0,-0.062733,-0.024983,-0.018913
2023-10-05,-0.046379,-0.049409,-0.015316,-0.053938,-0.045259,-0.042839,-0.057439,-0.035859,-0.079612,-0.021591,-0.059796,-0.027682,-0.048325,-0.019824,-0.046263,-0.070439,-0.065390,-0.032229,-0.072243,-0.016379,-0.000226,-0.067359,-0.055477,0.0,-0.061942,-0.096484,-0.028566
2023-11-03,0.023721,0.045706,0.007368,0.039836,0.018687,0.000232,0.016969,0.033570,0.051160,0.016766,0.028920,0.041421,0.054085,0.016548,0.008345,0.034017,0.044632,0.013371,0.025051,0.020542,-0.000226,0.028731,0.091868,0.0,0.114365,0.093799,0.041372
2023-12-05,0.049175,0.000323,0.032347,0.038595,0.053255,0.055176,0.092699,0.024010,0.067067,0.100846,-0.071480,0.097755,0.051309,-0.018775,0.057392,0.037008,0.038370,0.011446,-0.055867,0.052386,0.068283,0.030858,0.056078,0.0,-0.020691,0.063299,-0.003777

### Investment Cycle

In [29]:
indicator = 'Economic Cycle X'
df_investing_indicator = data_provider.get_key_indicator_values(indicator)
df_investing_indicator

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
1999-02-01,-0.562500,-2.995000,-3.068750,0.091250,-0.115000,-2.562500,-1.032500,-0.166250,0.252500,-1.625000,-1.868750,0.922500,-0.372500,-1.187500,-3.721250,-1.760000,-1.331250,-1.068750,-0.755000,-1.650000,-1.086250,2.958750,-3.263750,-0.011250,-2.673750,-2.067500,-1.411250
1999-03-01,-0.387755,-2.895510,-2.737755,0.182449,-0.163469,-1.918367,-1.117959,-0.112041,0.246122,-0.132653,-1.583673,1.007959,-0.335510,-0.964286,-3.536939,-1.601837,-1.126531,-0.992857,-0.828980,-1.364286,-0.955510,2.433878,-3.129184,0.341429,-2.712653,-1.323878,-1.344286
1999-04-01,-0.227941,-2.782684,-2.224081,0.296213,-0.148088,-0.485294,-1.169449,0.022169,0.243309,1.352941,-1.251103,1.059449,-0.250257,-0.723346,-3.377500,-1.334449,-0.815625,-0.968566,-0.925956,-1.059007,-0.796728,1.724375,-2.913566,0.726801,-2.716029,-0.628162,-1.213640
1999-05-01,-0.055344,-2.651402,-1.632443,0.453997,-0.044823,0.505899,-1.178362,0.177370,0.250548,1.503470,-0.873282,1.090049,-0.054969,-0.452984,-3.183407,-1.098307,-0.505239,-0.982200,-0.997106,-0.729806,-0.628994,0.972130,-2.547689,1.157578,-2.674379,-0.069452,-1.016884
1999-06-01,0.097946,-2.503962,-1.245408,0.645325,0.183771,1.426490,-1.124505,0.274976,0.288080,3.474020,-0.519462,1.102615,0.232427,-0.149637,-2.917645,-0.868251,-0.255491,-1.002256,-1.002516,-0.398422,-0.453194,0.346069,-2.061951,1.540408,-2.580235,0.379264,-0.812599
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-01,-1.874586,-0.342651,-4.963480,-1.137701,-4.097699,-8.403613,-9.585967,-0.746261,0.231548,-4.322714,0.181326,-2.424176,-4.524387,-3.318823,-0.694859,-2.621139,-1.960207,1.637648,-0.499792,-5.323930,8.002302,-1.282222,-1.712147,2.630556,-1.209637,0.973958,-2.311162
2023-09-01,-1.204752,-0.805590,-5.258088,-1.682621,-4.778619,-7.082168,-9.911580,-0.967757,0.126929,-5.273629,-0.051204,-2.374505,-3.994632,-3.595294,-0.468916,-2.848684,-2.040124,1.982589,-0.219875,-4.634358,7.801381,-0.809333,-1.427288,3.378334,-2.565782,0.504375,-2.534697
2023-10-01,-0.722851,-1.003354,-5.234853,-1.569572,-5.747172,-8.009301,-9.626948,-1.300654,0.072157,-4.884177,-0.470723,-3.384703,-4.436779,-4.141176,-0.369349,-3.005210,-2.084074,0.349553,-0.331925,-3.740615,6.880829,-0.565600,-1.416373,3.547000,-3.379469,1.142625,-3.680818
2023-11-01,-0.673711,-1.282013,-4.260912,-1.861743,-6.288303,-7.965581,-8.736169,-1.700392,0.043294,-3.330506,-0.242434,-3.510822,-4.902068,-4.092706,-0.377610,-3.099126,-2.078445,0.169732,-0.439155,-2.924369,6.528497,-0.339360,-1.089824,3.648200,-2.747682,1.685575,-2.980491
2023-12-01,-1.244226,-1.609208,-4.076547,-2.957046,-6.932982,-7.579348,-7.921701,-1.980235,-0.018023,-2.478304,0.374540,-3.626493,-4.821241,-4.327624,-0.322566,-3.143476,-1.955067,0.781839,-0.663493,-2.914621,5.877098,-0.243616,-1.293894,4.028920,-1.288609,1.811345,-2.540295

Indicator calculated without delay as rebalancing happens after the last PMI

In [30]:
data_provider.get_latest_data(indicator, df_investing_indicator, 
                              pd.to_datetime('2023-12-05'), 6)

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
2023-06-01,-2.207184,-0.240696,-2.876333,-0.671392,-3.671385,-4.454482,-7.049908,-1.361836,0.532077,-5.740873,1.125905,-1.378266,-3.789965,-2.461176,-2.379053,-2.058721,-1.585018,-1.473199,-0.588310,-4.522028,7.539727,-1.939505,-3.400408,2.907100,-1.226771,0.772105,-1.559894
2023-07-01,-1.724310,-0.304418,-3.605800,-0.562835,-4.162831,-7.272689,-8.709945,-0.977101,0.379246,-4.404524,0.435543,-1.706959,-4.473979,-3.224706,-1.271432,-2.355232,-1.807011,1.796080,-0.632986,-5.073217,7.603836,-1.403703,-2.920245,2.584260,-1.816062,0.823263,-1.931936
2023-08-01,-1.874586,-0.342651,-4.963480,-1.137701,-4.097699,-8.403613,-9.585967,-0.746261,0.231548,-4.322714,0.181326,-2.424176,-4.524387,-3.318823,-0.694859,-2.621139,-1.960207,1.637648,-0.499792,-5.323930,8.002302,-1.282222,-1.712147,2.630556,-1.209637,0.973958,-2.311162
2023-09-01,-1.204752,-0.805590,-5.258088,-1.682621,-4.778619,-7.082168,-9.911580,-0.967757,0.126929,-5.273629,-0.051204,-2.374505,-3.994632,-3.595294,-0.468916,-2.848684,-2.040124,1.982589,-0.219875,-4.634358,7.801381,-0.809333,-1.427288,3.378334,-2.565782,0.504375,-2.534697
2023-10-01,-0.722851,-1.003354,-5.234853,-1.569572,-5.747172,-8.009301,-9.626948,-1.300654,0.072157,-4.884177,-0.470723,-3.384703,-4.436779,-4.141176,-0.369349,-3.005210,-2.084074,0.349553,-0.331925,-3.740615,6.880829,-0.565600,-1.416373,3.547000,-3.379469,1.142625,-3.680818
2023-11-01,-0.673711,-1.282013,-4.260912,-1.861743,-6.288303,-7.965581,-8.736169,-1.700392,0.043294,-3.330506,-0.242434,-3.510822,-4.902068,-4.092706,-0.377610,-3.099126,-2.078445,0.169732,-0.439155,-2.924369,6.528497,-0.339360,-1.089824,3.648200,-2.747682,1.685575,-2.980491

In [31]:
indicator = 'Economic Cycle Y'
df_investing_indicator = data_provider.get_key_indicator_values(indicator)
df_investing_indicator

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
1999-02-01,0.187500,0.075000,0.181250,0.081250,-0.025000,0.937500,-0.112500,-0.056250,0.012500,0.375000,0.231250,0.012500,-0.012500,0.212500,0.168750,0.100000,0.168750,0.081250,-0.025000,0.250000,0.093750,-0.281250,0.106250,0.268750,-0.043750,0.712500,0.018750
1999-03-01,0.174745,0.099490,0.330995,0.091199,-0.048469,0.644133,-0.085459,0.054209,-0.006378,1.492347,0.285077,0.085459,0.036990,0.223214,0.184311,0.158163,0.204719,0.075893,-0.073980,0.285714,0.130740,-0.524872,0.134566,0.352679,-0.038903,0.743622,0.066964
1999-04-01,0.159814,0.112826,0.513674,0.113764,0.015381,1.433073,-0.051489,0.134210,-0.002814,1.485594,0.332571,0.051489,0.085253,0.240940,0.159439,0.267388,0.310906,0.024291,-0.096976,0.305278,0.158782,-0.709503,0.215617,0.385373,-0.003376,0.695716,0.130646
1999-05-01,0.172598,0.131282,0.591638,0.157784,0.103265,0.991193,-0.008914,0.155201,0.007239,0.150529,0.377820,0.030600,0.195289,0.270362,0.194093,0.236142,0.310386,-0.013634,-0.071150,0.329202,0.167734,-0.752245,0.365877,0.430777,0.041651,0.558710,0.196756
1999-06-01,0.153289,0.147440,0.387035,0.191328,0.228595,0.920592,0.053858,0.097606,0.037532,1.970550,0.353821,0.012567,0.287396,0.303347,0.265762,0.230056,0.249748,-0.020056,-0.005410,0.331383,0.175800,-0.626062,0.485738,0.382830,0.094144,0.448716,0.204285
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-08-01,-0.150276,-0.038233,-1.357680,-0.574866,0.065133,-1.130924,-0.876022,0.230841,-0.147698,0.081810,-0.254217,-0.717216,-0.050408,-0.094118,0.576573,-0.265907,-0.153196,-0.158432,0.133194,-0.250713,0.398465,0.121481,1.208098,0.046296,0.606425,0.150695,-0.379226
2023-09-01,0.669834,-0.462940,-0.294608,-0.544920,-0.680920,1.321445,-0.325613,-0.221496,-0.104619,-0.950914,-0.232530,0.049670,0.529755,-0.276471,0.225944,-0.227544,-0.079917,0.344941,0.279917,0.689572,-0.200921,0.472889,0.284859,0.747778,-1.356145,-0.469583,-0.223535
2023-10-01,0.481901,-0.197764,0.023235,0.113048,-0.968552,-0.927133,0.284632,-0.332897,-0.054771,0.389451,-0.419518,-1.010198,-0.442147,-0.545882,0.099566,-0.156527,-0.043950,-1.633036,-0.112050,0.893743,-0.920552,0.243733,0.010915,0.168667,-0.813687,0.638250,-1.146121
2023-11-01,0.049140,-0.278658,0.973941,-0.292171,-0.541131,0.043720,0.890779,-0.399738,-0.028863,1.553671,0.228289,-0.126119,-0.465288,0.048471,-0.008260,-0.093916,0.005630,-0.179821,-0.107230,0.816246,-0.352331,0.226240,0.326549,0.101200,0.631788,0.542950,0.700327
2023-12-01,-0.570516,-0.327195,0.184365,-1.095303,-0.644679,0.386232,0.814468,-0.279843,-0.061318,0.852203,0.616973,-0.115671,0.080827,-0.234918,0.055044,-0.044350,0.123378,0.612107,-0.224338,0.009748,-0.651399,0.095744,-0.204071,0.380720,1.459073,0.125770,0.440196

In [32]:
data_provider.get_latest_data(indicator, df_investing_indicator, 
                              pd.to_datetime('2023-12-05'), 6)

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Sweden,Hong Kong,Spain,Italy,Singapore,Denmark,Finland,Belgium,Norway,China,Taiwan,India,Korea,Brazil,Russia,South Africa,Mexico,Malaysia
2023-06-01,-0.995211,0.027131,-0.415778,-0.352406,-0.219076,-0.430345,-1.566728,-0.292109,-0.134718,0.360582,-0.550603,-0.414490,-1.606690,-0.499216,1.839369,-0.287519,-0.236655,-0.351201,-0.274460,-0.451981,0.173515,-0.173663,0.000272,-0.204734,-0.782153,0.085264,-0.900071
2023-07-01,0.482874,-0.063722,-0.729467,0.108557,-0.491446,-2.818207,-1.660037,0.384734,-0.152831,1.336349,-0.690362,-0.328694,-0.684014,-0.763530,1.107621,-0.296512,-0.221993,3.269280,-0.044676,-0.551189,0.064109,0.535802,0.480163,-0.322840,-0.589292,0.051158,-0.372043
2023-08-01,-0.150276,-0.038233,-1.357680,-0.574866,0.065133,-1.130924,-0.876022,0.230841,-0.147698,0.081810,-0.254217,-0.717216,-0.050408,-0.094118,0.576573,-0.265907,-0.153196,-0.158432,0.133194,-0.250713,0.398465,0.121481,1.208098,0.046296,0.606425,0.150695,-0.379226
2023-09-01,0.669834,-0.462940,-0.294608,-0.544920,-0.680920,1.321445,-0.325613,-0.221496,-0.104619,-0.950914,-0.232530,0.049670,0.529755,-0.276471,0.225944,-0.227544,-0.079917,0.344941,0.279917,0.689572,-0.200921,0.472889,0.284859,0.747778,-1.356145,-0.469583,-0.223535
2023-10-01,0.481901,-0.197764,0.023235,0.113048,-0.968552,-0.927133,0.284632,-0.332897,-0.054771,0.389451,-0.419518,-1.010198,-0.442147,-0.545882,0.099566,-0.156527,-0.043950,-1.633036,-0.112050,0.893743,-0.920552,0.243733,0.010915,0.168667,-0.813687,0.638250,-1.146121
2023-11-01,0.049140,-0.278658,0.973941,-0.292171,-0.541131,0.043720,0.890779,-0.399738,-0.028863,1.553671,0.228289,-0.126119,-0.465288,0.048471,-0.008260,-0.093916,0.005630,-0.179821,-0.107230,0.816246,-0.352331,0.226240,0.326549,0.101200,0.631788,0.542950,0.700327