In [2]:
import pandas as pd

In [18]:
monthly_unemployment = pd.read_csv('monthly_unemployment.csv', parse_dates=True, index_col=0)
monthly_unemployment

,United States,Japan,United Kingdom,Canada,France,Switzerland,Germany,Australia,Netherlands,Denmark,...,Indonesia,Turkiye,Poland,Chile,Greece,Hungary,Czechia,Colombia,Argentina,Russia
1999-01-01,4.3,4.5,6.2,7.9,12.0,3.5,8.9,7.1,4.6,5.0,...,NaN,NaN,11.5,8.4,11.4,7.2,7.8,NaN,NaN,NaN
1999-01-02,4.4,4.6,6.2,7.9,12.0,3.4,8.8,7.1,4.5,5.0,...,NaN,NaN,12.0,8.8,11.4,7.2,8.1,NaN,NaN,NaN
1999-01-03,4.2,4.7,6.2,7.9,11.8,3.2,8.8,7.0,4.4,5.0,...,NaN,NaN,12.3,9.3,11.4,7.1,8.6,NaN,NaN,NaN
1999-01-04,4.3,4.7,6.1,8.2,11.7,2.9,8.7,7.0,4.4,5.0,...,NaN,NaN,12.7,10.0,12.1,7.0,8.6,NaN,NaN,NaN
1999-01-05,4.2,4.7,6.0,7.9,11.5,2.7,8.6,7.0,4.3,5.0,...,NaN,NaN,12.9,10.6,12.0,6.9,8.7,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-04,3.4,2.6,3.8,5.0,7.3,2.0,2.9,3.7,3.4,5.0,...,NaN,10.0,2.8,8.3,11.6,3.9,2.7,10.3,NaN,NaN
2023-01-05,3.7,2.6,4.0,5.2,7.3,1.9,2.9,3.6,3.5,4.9,...,NaN,9.5,2.8,8.2,11.2,3.9,2.5,10.1,NaN,NaN
2023-01-06,3.6,2.5,4.2,5.4,7.3,1.9,2.9,3.5,3.5,4.9,...,NaN,9.6,2.8,8.4,11.0,3.9,2.7,9.4,NaN,NaN
2023-01-07,3.5,2.7,4.3,5.5,7.4,1.9,2.9,3.7,3.6,5.6,...,NaN,9.4,2.8,NaN,10.8,4.0,2.7,9.3,NaN,NaN
2023-01-08,3.8,NaN,NaN,5.5,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN